import { NextResponse } from "next/server";
import { getTeacherId } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const MIDDLE_WORDS: Record<string, { english: string; korean: string }[]> = {
  "중1": [
    { english: "ability", korean: "능력" }, { english: "absent", korean: "결석한" }, { english: "accident", korean: "사고" },
    { english: "address", korean: "주소" }, { english: "adult", korean: "어른" }, { english: "adventure", korean: "모험" },
    { english: "afraid", korean: "두려운" }, { english: "age", korean: "나이" }, { english: "ago", korean: "전에" },
    { english: "agree", korean: "동의하다" }, { english: "ahead", korean: "앞에" }, { english: "alarm", korean: "알람" },
    { english: "alone", korean: "혼자" }, { english: "already", korean: "이미" }, { english: "although", korean: "비록 ~이지만" },
    { english: "always", korean: "항상" }, { english: "angry", korean: "화난" }, { english: "another", korean: "또 다른" },
    { english: "answer", korean: "대답" }, { english: "anxious", korean: "불안한" }, { english: "appear", korean: "나타나다" },
    { english: "arrive", korean: "도착하다" }, { english: "athlete", korean: "운동선수" }, { english: "attack", korean: "공격하다" },
    { english: "audience", korean: "관객" }, { english: "autumn", korean: "가을" }, { english: "available", korean: "이용 가능한" },
    { english: "award", korean: "상" }, { english: "awesome", korean: "굉장한" }, { english: "badly", korean: "심하게" },
    { english: "base", korean: "기초" }, { english: "basket", korean: "바구니" }, { english: "battery", korean: "배터리" },
    { english: "beach", korean: "해변" }, { english: "bear", korean: "곰" }, { english: "beat", korean: "이기다" },
    { english: "beautiful", korean: "아름다운" }, { english: "become", korean: "되다" }, { english: "begin", korean: "시작하다" },
    { english: "believe", korean: "믿다" }, { english: "belong", korean: "속하다" }, { english: "between", korean: "사이에" },
    { english: "board", korean: "판" }, { english: "boring", korean: "지루한" }, { english: "borrow", korean: "빌리다" },
    { english: "bottle", korean: "병" }, { english: "brave", korean: "용감한" }, { english: "bright", korean: "밝은" },
    { english: "bring", korean: "가져오다" }, { english: "build", korean: "짓다" }, { english: "busy", korean: "바쁜" },
    { english: "button", korean: "단추" }, { english: "calendar", korean: "달력" }, { english: "camera", korean: "카메라" },
    { english: "camp", korean: "캠프" }, { english: "care", korean: "돌보다" }, { english: "careful", korean: "조심스러운" },
    { english: "carry", korean: "운반하다" }, { english: "catch", korean: "잡다" }, { english: "cause", korean: "원인" },
    { english: "celebrate", korean: "축하하다" }, { english: "center", korean: "중심" }, { english: "chance", korean: "기회" },
    { english: "change", korean: "변하다" }, { english: "character", korean: "성격" }, { english: "cheap", korean: "저렴한" },
    { english: "check", korean: "확인하다" }, { english: "choose", korean: "선택하다" }, { english: "class", korean: "수업" },
    { english: "classmate", korean: "반 친구" }, { english: "clean", korean: "깨끗한" }, { english: "clear", korean: "맑은" },
    { english: "climb", korean: "오르다" }, { english: "close", korean: "닫다" }, { english: "cloud", korean: "구름" },
    { english: "collect", korean: "모으다" }, { english: "color", korean: "색깔" }, { english: "come", korean: "오다" },
    { english: "comfort", korean: "편안함" }, { english: "complete", korean: "완성하다" }, { english: "concert", korean: "콘서트" },
    { english: "cook", korean: "요리하다" }, { english: "cool", korean: "시원한" }, { english: "copy", korean: "베끼다" },
    { english: "corner", korean: "모퉁이" }, { english: "correct", korean: "올바른" }, { english: "count", korean: "세다" },
    { english: "country", korean: "나라" }, { english: "couple", korean: "몇몇" }, { english: "course", korean: "과정" },
    { english: "cover", korean: "덮다" }, { english: "create", korean: "창조하다" }, { english: "cross", korean: "건너다" },
    { english: "crowd", korean: "군중" }, { english: "culture", korean: "문화" }, { english: "cute", korean: "귀여운" },
    { english: "daily", korean: "매일의" }, { english: "danger", korean: "위험" }, { english: "dark", korean: "어두운" },
    { english: "decide", korean: "결정하다" }, { english: "delicious", korean: "맛있는" }, { english: "deliver", korean: "배달하다" },
    { english: "describe", korean: "묘사하다" }, { english: "different", korean: "다른" }, { english: "difficult", korean: "어려운" },
    { english: "dinner", korean: "저녁 식사" }, { english: "discover", korean: "발견하다" }, { english: "discuss", korean: "토론하다" },
    { english: "distance", korean: "거리" }, { english: "dizzy", korean: "어지러운" }, { english: "draw", korean: "그리다" },
    { english: "dream", korean: "꿈" }, { english: "during", korean: "~동안" }, { english: "early", korean: "일찍" },
    { english: "earth", korean: "지구" }, { english: "east", korean: "동쪽" }, { english: "easy", korean: "쉬운" },
    { english: "either", korean: "둘 중 하나" }, { english: "else", korean: "그 밖의" }, { english: "empty", korean: "빈" },
    { english: "enjoy", korean: "즐기다" }, { english: "enough", korean: "충분한" }, { english: "enter", korean: "들어가다" },
    { english: "eraser", korean: "지우개" }, { english: "evening", korean: "저녁" }, { english: "everyone", korean: "모든 사람" },
    { english: "everything", korean: "모든 것" }, { english: "excited", korean: "신난" }, { english: "exercise", korean: "운동" },
    { english: "experience", korean: "경험" }, { english: "explain", korean: "설명하다" }, { english: "extra", korean: "추가의" },
    { english: "face", korean: "얼굴" }, { english: "fact", korean: "사실" }, { english: "fail", korean: "실패하다" },
    { english: "fair", korean: "공정한" }, { english: "fall", korean: "떨어지다" }, { english: "famous", korean: "유명한" },
    { english: "fantastic", korean: "환상적인" }, { english: "farm", korean: "농장" }, { english: "fast", korean: "빠른" },
    { english: "favorite", korean: "가장 좋아하는" }, { english: "festival", korean: "축제" }, { english: "field", korean: "들판" },
    { english: "fight", korean: "싸우다" }, { english: "finish", korean: "끝내다" }, { english: "first", korean: "첫 번째" },
    { english: "floor", korean: "바닥" }, { english: "flower", korean: "꽃" }, { english: "follow", korean: "따르다" },
    { english: "foreign", korean: "외국의" }, { english: "forget", korean: "잊다" }, { english: "free", korean: "자유로운" },
    { english: "fresh", korean: "신선한" }, { english: "friendly", korean: "친절한" }, { english: "front", korean: "앞" },
    { english: "fruit", korean: "과일" }, { english: "full", korean: "가득 찬" }, { english: "funny", korean: "재미있는" },
    { english: "future", korean: "미래" }, { english: "garden", korean: "정원" }, { english: "gentle", korean: "온화한" },
    { english: "gift", korean: "선물" }, { english: "glad", korean: "기쁜" }, { english: "goal", korean: "목표" },
    { english: "great", korean: "훌륭한" }, { english: "group", korean: "그룹" }, { english: "grow", korean: "자라다" },
    { english: "guess", korean: "추측하다" }, { english: "guest", korean: "손님" }, { english: "guide", korean: "안내하다" },
    { english: "habit", korean: "습관" }, { english: "happen", korean: "일어나다" }, { english: "hard", korean: "어려운" },
    { english: "hate", korean: "싫어하다" }, { english: "health", korean: "건강" }, { english: "heavy", korean: "무거운" },
    { english: "helpful", korean: "도움이 되는" }, { english: "here", korean: "여기에" }, { english: "high", korean: "높은" },
    { english: "hobby", korean: "취미" }, { english: "holiday", korean: "휴일" }, { english: "honest", korean: "정직한" },
    { english: "hour", korean: "시간" }, { english: "human", korean: "인간" }, { english: "hungry", korean: "배고픈" },
    { english: "hurt", korean: "다치게 하다" }, { english: "idea", korean: "생각" }, { english: "important", korean: "중요한" },
    { english: "include", korean: "포함하다" }, { english: "inside", korean: "안에" }, { english: "instead", korean: "대신에" },
    { english: "introduce", korean: "소개하다" }, { english: "invite", korean: "초대하다" }, { english: "island", korean: "섬" },
    { english: "join", korean: "참가하다" }, { english: "jump", korean: "뛰다" }, { english: "just", korean: "그냥" },
    { english: "keep", korean: "유지하다" }, { english: "kind", korean: "친절한" }, { english: "knock", korean: "두드리다" },
    { english: "language", korean: "언어" }, { english: "large", korean: "큰" }, { english: "last", korean: "마지막의" },
    { english: "late", korean: "늦은" }, { english: "laugh", korean: "웃다" }, { english: "lazy", korean: "게으른" },
    { english: "lead", korean: "이끌다" }, { english: "leave", korean: "떠나다" }, { english: "lesson", korean: "수업" },
    { english: "letter", korean: "편지" }, { english: "level", korean: "수준" }, { english: "library", korean: "도서관" },
    { english: "life", korean: "삶" }, { english: "light", korean: "빛" }, { english: "line", korean: "줄" },
    { english: "listen", korean: "듣다" }, { english: "little", korean: "조금" }, { english: "local", korean: "지역의" },
    { english: "lonely", korean: "외로운" }, { english: "loud", korean: "시끄러운" }, { english: "lovely", korean: "사랑스러운" },
    { english: "lucky", korean: "운이 좋은" }, { english: "lunch", korean: "점심" }, { english: "main", korean: "주요한" },
    { english: "manager", korean: "관리자" }, { english: "many", korean: "많은" }, { english: "matter", korean: "중요하다" },
    { english: "meal", korean: "식사" }, { english: "mean", korean: "의미하다" }, { english: "memory", korean: "기억" },
    { english: "message", korean: "메시지" }, { english: "midnight", korean: "자정" }, { english: "minute", korean: "분" },
    { english: "miss", korean: "그리워하다" }, { english: "mistake", korean: "실수" }, { english: "mix", korean: "섞다" },
    { english: "modern", korean: "현대의" }, { english: "most", korean: "가장" }, { english: "move", korean: "움직이다" },
    { english: "museum", korean: "박물관" }, { english: "music", korean: "음악" }, { english: "natural", korean: "자연적인" },
    { english: "nearby", korean: "근처에" }, { english: "need", korean: "필요하다" }, { english: "never", korean: "절대" },
    { english: "next", korean: "다음의" }, { english: "nice", korean: "좋은" }, { english: "noise", korean: "소음" },
    { english: "north", korean: "북쪽" }, { english: "nothing", korean: "아무것도 없는" }, { english: "notice", korean: "알아채다" },
    { english: "often", korean: "자주" }, { english: "once", korean: "한번" }, { english: "open", korean: "열다" },
    { english: "order", korean: "주문하다" }, { english: "other", korean: "다른" }, { english: "outside", korean: "밖에" },
    { english: "own", korean: "자신의" }, { english: "page", korean: "페이지" }, { english: "paint", korean: "그리다" },
    { english: "paper", korean: "종이" }, { english: "parent", korean: "부모" }, { english: "part", korean: "부분" },
    { english: "pass", korean: "통과하다" }, { english: "patient", korean: "참을성 있는" }, { english: "peace", korean: "평화" },
    { english: "people", korean: "사람들" }, { english: "pick", korean: "고르다" }, { english: "picture", korean: "사진" },
    { english: "place", korean: "장소" }, { english: "plan", korean: "계획" }, { english: "plant", korean: "식물" },
    { english: "player", korean: "선수" }, { english: "pleased", korean: "기쁜" }, { english: "popular", korean: "인기 있는" },
    { english: "possible", korean: "가능한" }, { english: "practice", korean: "연습하다" }, { english: "prepare", korean: "준비하다" },
    { english: "present", korean: "선물" }, { english: "pretty", korean: "예쁜" }, { english: "price", korean: "가격" },
    { english: "problem", korean: "문제" }, { english: "proud", korean: "자랑스러운" }, { english: "pull", korean: "당기다" },
    { english: "push", korean: "밀다" }, { english: "put", korean: "놓다" }, { english: "quick", korean: "빠른" },
    { english: "quiet", korean: "조용한" }, { english: "raise", korean: "올리다" }, { english: "reach", korean: "닿다" },
    { english: "ready", korean: "준비된" }, { english: "real", korean: "진짜의" }, { english: "reason", korean: "이유" },
    { english: "receive", korean: "받다" }, { english: "remember", korean: "기억하다" }, { english: "repeat", korean: "반복하다" },
    { english: "rest", korean: "쉬다" }, { english: "return", korean: "돌아오다" }, { english: "ride", korean: "타다" },
    { english: "right", korean: "오른쪽" }, { english: "road", korean: "길" }, { english: "role", korean: "역할" },
    { english: "round", korean: "둥근" }, { english: "rule", korean: "규칙" }, { english: "safe", korean: "안전한" },
    { english: "same", korean: "같은" }, { english: "save", korean: "저장하다" }, { english: "scared", korean: "무서운" },
    { english: "scene", korean: "장면" }, { english: "school", korean: "학교" }, { english: "science", korean: "과학" },
    { english: "second", korean: "두 번째" }, { english: "seem", korean: "~처럼 보이다" }, { english: "send", korean: "보내다" },
    { english: "serious", korean: "심각한" }, { english: "shape", korean: "모양" }, { english: "share", korean: "공유하다" },
    { english: "sharp", korean: "날카로운" }, { english: "shine", korean: "빛나다" }, { english: "shop", korean: "가게" },
    { english: "short", korean: "짧은" }, { english: "shout", korean: "소리치다" }, { english: "show", korean: "보여주다" },
    { english: "sick", korean: "아픈" }, { english: "sign", korean: "표시" }, { english: "similar", korean: "비슷한" },
    { english: "simple", korean: "간단한" }, { english: "since", korean: "~이후로" }, { english: "singer", korean: "가수" },
    { english: "skill", korean: "기술" }, { english: "sleep", korean: "자다" }, { english: "slow", korean: "느린" },
    { english: "smell", korean: "냄새" }, { english: "smile", korean: "웃다" }, { english: "snow", korean: "눈" },
    { english: "soft", korean: "부드러운" }, { english: "solve", korean: "해결하다" }, { english: "something", korean: "무언가" },
    { english: "sometimes", korean: "때때로" }, { english: "soon", korean: "곧" }, { english: "sound", korean: "소리" },
    { english: "south", korean: "남쪽" }, { english: "space", korean: "공간" }, { english: "speak", korean: "말하다" },
    { english: "special", korean: "특별한" }, { english: "spend", korean: "보내다" }, { english: "spread", korean: "퍼지다" },
    { english: "stadium", korean: "경기장" }, { english: "start", korean: "시작하다" }, { english: "stay", korean: "머물다" },
    { english: "still", korean: "여전히" }, { english: "store", korean: "가게" }, { english: "story", korean: "이야기" },
    { english: "strange", korean: "이상한" }, { english: "street", korean: "거리" }, { english: "strong", korean: "강한" },
    { english: "student", korean: "학생" }, { english: "study", korean: "공부하다" }, { english: "subject", korean: "과목" },
    { english: "surprise", korean: "놀라게 하다" }, { english: "sweet", korean: "달콤한" }, { english: "swim", korean: "수영하다" },
    { english: "table", korean: "테이블" }, { english: "taste", korean: "맛" }, { english: "teach", korean: "가르치다" },
    { english: "team", korean: "팀" }, { english: "terrible", korean: "끔찍한" }, { english: "thankful", korean: "감사하는" },
    { english: "thick", korean: "두꺼운" }, { english: "thin", korean: "얇은" }, { english: "think", korean: "생각하다" },
    { english: "through", korean: "~을 통해" }, { english: "tired", korean: "피곤한" }, { english: "together", korean: "함께" },
    { english: "town", korean: "마을" }, { english: "travel", korean: "여행하다" }, { english: "trip", korean: "여행" },
    { english: "trouble", korean: "문제" }, { english: "true", korean: "진실의" }, { english: "turn", korean: "돌다" },
    { english: "twice", korean: "두 번" }, { english: "type", korean: "종류" }, { english: "under", korean: "아래에" },
    { english: "understand", korean: "이해하다" }, { english: "useful", korean: "유용한" }, { english: "usually", korean: "보통" },
    { english: "view", korean: "전망" }, { english: "visit", korean: "방문하다" }, { english: "voice", korean: "목소리" },
    { english: "wait", korean: "기다리다" }, { english: "watch", korean: "보다" }, { english: "weather", korean: "날씨" },
    { english: "weight", korean: "무게" }, { english: "west", korean: "서쪽" }, { english: "while", korean: "~하는 동안" },
    { english: "wide", korean: "넓은" }, { english: "win", korean: "이기다" }, { english: "wish", korean: "바라다" },
    { english: "wonder", korean: "궁금하다" }, { english: "word", korean: "단어" }, { english: "worry", korean: "걱정하다" },
    { english: "write", korean: "쓰다" }, { english: "wrong", korean: "틀린" }, { english: "yesterday", korean: "어제" },
  ],
  "중2": [
    { english: "achieve", korean: "성취하다" }, { english: "adapt", korean: "적응하다" }, { english: "advertise", korean: "광고하다" },
    { english: "affect", korean: "영향을 주다" }, { english: "afford", korean: "여유가 있다" }, { english: "agent", korean: "대리인" },
    { english: "agriculture", korean: "농업" }, { english: "ancient", korean: "고대의" }, { english: "announce", korean: "발표하다" },
    { english: "anxiety", korean: "불안" }, { english: "apologize", korean: "사과하다" }, { english: "appreciate", korean: "감사하다" },
    { english: "approve", korean: "승인하다" }, { english: "architect", korean: "건축가" }, { english: "argue", korean: "논쟁하다" },
    { english: "arrange", korean: "정리하다" }, { english: "artificial", korean: "인공의" }, { english: "assist", korean: "돕다" },
    { english: "atmosphere", korean: "분위기" }, { english: "attach", korean: "붙이다" }, { english: "attempt", korean: "시도하다" },
    { english: "attitude", korean: "태도" }, { english: "attract", korean: "끌다" }, { english: "average", korean: "평균의" },
    { english: "avoid", korean: "피하다" }, { english: "aware", korean: "인식하는" }, { english: "balance", korean: "균형" },
    { english: "behavior", korean: "행동" }, { english: "benefit", korean: "혜택" }, { english: "blame", korean: "비난하다" },
    { english: "blend", korean: "섞다" }, { english: "block", korean: "막다" }, { english: "border", korean: "경계" },
    { english: "breathe", korean: "숨 쉬다" }, { english: "broadcast", korean: "방송하다" }, { english: "budget", korean: "예산" },
    { english: "capital", korean: "수도" }, { english: "career", korean: "직업" }, { english: "category", korean: "범주" },
    { english: "challenge", korean: "도전" }, { english: "citizen", korean: "시민" }, { english: "claim", korean: "주장하다" },
    { english: "climate", korean: "기후" }, { english: "collect", korean: "수집하다" }, { english: "combine", korean: "결합하다" },
    { english: "communicate", korean: "소통하다" }, { english: "community", korean: "지역 사회" }, { english: "compare", korean: "비교하다" },
    { english: "competition", korean: "경쟁" }, { english: "concentrate", korean: "집중하다" }, { english: "concern", korean: "걱정" },
    { english: "condition", korean: "조건" }, { english: "confident", korean: "자신 있는" }, { english: "conflict", korean: "갈등" },
    { english: "connect", korean: "연결하다" }, { english: "consider", korean: "고려하다" }, { english: "consume", korean: "소비하다" },
    { english: "contain", korean: "포함하다" }, { english: "content", korean: "내용" }, { english: "control", korean: "통제하다" },
    { english: "convenient", korean: "편리한" }, { english: "creative", korean: "창의적인" }, { english: "crime", korean: "범죄" },
    { english: "curious", korean: "호기심 많은" }, { english: "custom", korean: "관습" }, { english: "damage", korean: "손상" },
    { english: "debate", korean: "토론하다" }, { english: "decade", korean: "10년" }, { english: "decrease", korean: "감소하다" },
    { english: "define", korean: "정의하다" }, { english: "delay", korean: "지연시키다" }, { english: "demand", korean: "요구하다" },
    { english: "democracy", korean: "민주주의" }, { english: "depend", korean: "의존하다" }, { english: "develop", korean: "발전시키다" },
    { english: "device", korean: "기기" }, { english: "diet", korean: "식단" }, { english: "disagree", korean: "동의하지 않다" },
    { english: "disappear", korean: "사라지다" }, { english: "discipline", korean: "훈련" }, { english: "disease", korean: "질병" },
    { english: "divide", korean: "나누다" }, { english: "document", korean: "문서" }, { english: "earn", korean: "벌다" },
    { english: "ecosystem", korean: "생태계" }, { english: "educate", korean: "교육하다" }, { english: "effective", korean: "효과적인" },
    { english: "emotion", korean: "감정" }, { english: "energy", korean: "에너지" }, { english: "engineer", korean: "기술자" },
    { english: "environment", korean: "환경" }, { english: "equal", korean: "평등한" }, { english: "establish", korean: "설립하다" },
    { english: "event", korean: "행사" }, { english: "evidence", korean: "증거" }, { english: "examine", korean: "검사하다" },
    { english: "excellent", korean: "훌륭한" }, { english: "exist", korean: "존재하다" }, { english: "expand", korean: "확장하다" },
    { english: "expect", korean: "기대하다" }, { english: "experiment", korean: "실험" }, { english: "expert", korean: "전문가" },
    { english: "explore", korean: "탐험하다" }, { english: "express", korean: "표현하다" }, { english: "extend", korean: "늘리다" },
    { english: "extreme", korean: "극단적인" }, { english: "factor", korean: "요인" }, { english: "fault", korean: "잘못" },
    { english: "feature", korean: "특징" }, { english: "focus", korean: "집중하다" }, { english: "force", korean: "강요하다" },
    { english: "forecast", korean: "예보" }, { english: "formal", korean: "공식적인" }, { english: "found", korean: "설립하다" },
    { english: "freedom", korean: "자유" }, { english: "frequent", korean: "자주 있는" }, { english: "function", korean: "기능" },
    { english: "gain", korean: "얻다" }, { english: "general", korean: "일반적인" }, { english: "generate", korean: "만들어 내다" },
    { english: "global", korean: "세계적인" }, { english: "government", korean: "정부" }, { english: "gradually", korean: "점차" },
    { english: "grateful", korean: "감사하는" }, { english: "guarantee", korean: "보증하다" }, { english: "guilty", korean: "죄책감이 있는" },
    { english: "habitat", korean: "서식지" }, { english: "harmful", korean: "해로운" }, { english: "harvest", korean: "수확하다" },
    { english: "heritage", korean: "유산" }, { english: "highlight", korean: "강조하다" }, { english: "hire", korean: "고용하다" },
    { english: "homeless", korean: "집 없는" }, { english: "hunger", korean: "굶주림" }, { english: "identify", korean: "확인하다" },
    { english: "illegal", korean: "불법의" }, { english: "imagine", korean: "상상하다" }, { english: "improve", korean: "향상시키다" },
    { english: "increase", korean: "증가하다" }, { english: "independence", korean: "독립" }, { english: "indicate", korean: "나타내다" },
    { english: "influence", korean: "영향" }, { english: "inform", korean: "알리다" }, { english: "injury", korean: "부상" },
    { english: "inspire", korean: "영감을 주다" }, { english: "instrument", korean: "악기" }, { english: "interact", korean: "상호작용하다" },
    { english: "invention", korean: "발명품" }, { english: "investigate", korean: "조사하다" }, { english: "involve", korean: "관련시키다" },
    { english: "issue", korean: "문제" }, { english: "journey", korean: "여정" }, { english: "justice", korean: "정의" },
    { english: "knowledge", korean: "지식" }, { english: "landscape", korean: "풍경" }, { english: "launch", korean: "시작하다" },
    { english: "layer", korean: "층" }, { english: "limit", korean: "제한하다" }, { english: "literature", korean: "문학" },
    { english: "location", korean: "위치" }, { english: "logical", korean: "논리적인" }, { english: "maintain", korean: "유지하다" },
    { english: "major", korean: "주요한" }, { english: "manage", korean: "관리하다" }, { english: "manufacture", korean: "제조하다" },
    { english: "material", korean: "재료" }, { english: "mental", korean: "정신적인" }, { english: "method", korean: "방법" },
    { english: "migrate", korean: "이동하다" }, { english: "mission", korean: "임무" }, { english: "multiple", korean: "다수의" },
    { english: "nation", korean: "국가" }, { english: "nature", korean: "자연" }, { english: "necessary", korean: "필요한" },
    { english: "negative", korean: "부정적인" }, { english: "nervous", korean: "긴장한" }, { english: "novel", korean: "소설" },
    { english: "objective", korean: "목표" }, { english: "observe", korean: "관찰하다" }, { english: "occur", korean: "발생하다" },
    { english: "official", korean: "공식적인" }, { english: "opportunity", korean: "기회" }, { english: "organization", korean: "조직" },
    { english: "original", korean: "독창적인" }, { english: "overcome", korean: "극복하다" }, { english: "participate", korean: "참여하다" },
    { english: "passion", korean: "열정" }, { english: "pattern", korean: "패턴" }, { english: "perform", korean: "공연하다" },
    { english: "period", korean: "기간" }, { english: "personality", korean: "성격" }, { english: "physical", korean: "신체적인" },
    { english: "planet", korean: "행성" }, { english: "policy", korean: "정책" }, { english: "pollution", korean: "오염" },
    { english: "population", korean: "인구" }, { english: "positive", korean: "긍정적인" }, { english: "poverty", korean: "빈곤" },
    { english: "powerful", korean: "강력한" }, { english: "predict", korean: "예측하다" }, { english: "prevent", korean: "예방하다" },
    { english: "priority", korean: "우선순위" }, { english: "process", korean: "과정" }, { english: "produce", korean: "생산하다" },
    { english: "progress", korean: "진전" }, { english: "project", korean: "프로젝트" }, { english: "promote", korean: "홍보하다" },
    { english: "protect", korean: "보호하다" }, { english: "provide", korean: "제공하다" }, { english: "publish", korean: "출판하다" },
    { english: "purpose", korean: "목적" }, { english: "quality", korean: "품질" }, { english: "range", korean: "범위" },
    { english: "reduce", korean: "줄이다" }, { english: "reflect", korean: "반영하다" }, { english: "region", korean: "지역" },
    { english: "relationship", korean: "관계" }, { english: "release", korean: "발표하다" }, { english: "religion", korean: "종교" },
    { english: "replace", korean: "교체하다" }, { english: "report", korean: "보고하다" }, { english: "require", korean: "요구하다" },
    { english: "research", korean: "연구" }, { english: "resource", korean: "자원" }, { english: "respect", korean: "존중하다" },
    { english: "result", korean: "결과" }, { english: "review", korean: "검토하다" }, { english: "revolution", korean: "혁명" },
    { english: "reward", korean: "보상" }, { english: "risk", korean: "위험" }, { english: "robot", korean: "로봇" },
    { english: "routine", korean: "일상" }, { english: "satisfy", korean: "만족시키다" }, { english: "secret", korean: "비밀" },
    { english: "section", korean: "구역" }, { english: "select", korean: "선택하다" }, { english: "separate", korean: "분리하다" },
    { english: "shortage", korean: "부족" }, { english: "situation", korean: "상황" }, { english: "society", korean: "사회" },
    { english: "solution", korean: "해결책" }, { english: "species", korean: "종" }, { english: "spread", korean: "퍼뜨리다" },
    { english: "standard", korean: "기준" }, { english: "statement", korean: "진술" }, { english: "strategy", korean: "전략" },
    { english: "structure", korean: "구조" }, { english: "struggle", korean: "고투하다" }, { english: "succeed", korean: "성공하다" },
    { english: "suggest", korean: "제안하다" }, { english: "support", korean: "지지하다" }, { english: "surround", korean: "둘러싸다" },
    { english: "survival", korean: "생존" }, { english: "symbol", korean: "상징" }, { english: "system", korean: "시스템" },
    { english: "talent", korean: "재능" }, { english: "technology", korean: "기술" }, { english: "tension", korean: "긴장" },
    { english: "theory", korean: "이론" }, { english: "threat", korean: "위협" }, { english: "tradition", korean: "전통" },
    { english: "transform", korean: "변환하다" }, { english: "transport", korean: "운반하다" }, { english: "trend", korean: "추세" },
    { english: "trust", korean: "신뢰하다" }, { english: "universe", korean: "우주" }, { english: "unless", korean: "~하지 않으면" },
    { english: "update", korean: "업데이트하다" }, { english: "valuable", korean: "가치 있는" }, { english: "variety", korean: "다양성" },
    { english: "violence", korean: "폭력" }, { english: "virtual", korean: "가상의" }, { english: "visible", korean: "보이는" },
    { english: "volunteer", korean: "자원봉사하다" }, { english: "waste", korean: "낭비하다" }, { english: "wealth", korean: "부" },
    { english: "welfare", korean: "복지" }, { english: "whereas", korean: "반면에" }, { english: "widespread", korean: "광범위한" },
    { english: "willing", korean: "기꺼이 하는" }, { english: "wisdom", korean: "지혜" }, { english: "witness", korean: "목격하다" },
    { english: "worth", korean: "~할 가치가 있는" },
  ],
  "중3": [
    { english: "abolish", korean: "폐지하다" }, { english: "abstract", korean: "추상적인" }, { english: "accelerate", korean: "가속하다" },
    { english: "accessible", korean: "접근 가능한" }, { english: "accommodate", korean: "수용하다" }, { english: "accurate", korean: "정확한" },
    { english: "acknowledge", korean: "인정하다" }, { english: "acquire", korean: "얻다" }, { english: "adequate", korean: "충분한" },
    { english: "adjust", korean: "조정하다" }, { english: "administration", korean: "행정" }, { english: "advocate", korean: "지지하다" },
    { english: "aesthetic", korean: "미적인" }, { english: "aggression", korean: "공격성" }, { english: "allocate", korean: "할당하다" },
    { english: "alternative", korean: "대안" }, { english: "ambiguous", korean: "모호한" }, { english: "ambitious", korean: "야망 있는" },
    { english: "analyze", korean: "분석하다" }, { english: "anticipate", korean: "예상하다" }, { english: "apparent", korean: "명백한" },
    { english: "appropriate", korean: "적절한" }, { english: "approximately", korean: "약" }, { english: "arbitrary", korean: "임의적인" },
    { english: "assess", korean: "평가하다" }, { english: "assumption", korean: "가정" }, { english: "assure", korean: "보장하다" },
    { english: "authority", korean: "권위" }, { english: "bankruptcy", korean: "파산" }, { english: "barrier", korean: "장벽" },
    { english: "bias", korean: "편견" }, { english: "biodiversity", korean: "생물 다양성" }, { english: "breakthrough", korean: "돌파구" },
    { english: "capitalism", korean: "자본주의" }, { english: "catastrophe", korean: "재앙" }, { english: "cease", korean: "그치다" },
    { english: "censorship", korean: "검열" }, { english: "circumstance", korean: "상황" }, { english: "collaborate", korean: "협력하다" },
    { english: "collision", korean: "충돌" }, { english: "commitment", korean: "헌신" }, { english: "commodity", korean: "상품" },
    { english: "compensate", korean: "보상하다" }, { english: "competent", korean: "유능한" }, { english: "complement", korean: "보완하다" },
    { english: "complex", korean: "복잡한" }, { english: "comply", korean: "따르다" }, { english: "concept", korean: "개념" },
    { english: "conclude", korean: "결론짓다" }, { english: "consequence", korean: "결과" }, { english: "consistency", korean: "일관성" },
    { english: "construct", korean: "건설하다" }, { english: "contradict", korean: "반박하다" }, { english: "contribute", korean: "기여하다" },
    { english: "controversy", korean: "논란" }, { english: "convert", korean: "전환하다" }, { english: "cooperate", korean: "협력하다" },
    { english: "coordinate", korean: "조율하다" }, { english: "counterpart", korean: "상대방" }, { english: "credible", korean: "신뢰할 수 있는" },
    { english: "critical", korean: "비판적인" }, { english: "crucial", korean: "중요한" }, { english: "cultivate", korean: "경작하다" },
    { english: "curriculum", korean: "교육과정" }, { english: "decay", korean: "부패하다" }, { english: "dedicate", korean: "헌신하다" },
    { english: "defend", korean: "방어하다" }, { english: "deforestation", korean: "삼림 벌채" }, { english: "deliberate", korean: "신중한" },
    { english: "demonstrate", korean: "증명하다" }, { english: "deny", korean: "부정하다" }, { english: "detect", korean: "감지하다" },
    { english: "deter", korean: "막다" }, { english: "devote", korean: "헌신하다" }, { english: "dilemma", korean: "딜레마" },
    { english: "diminish", korean: "줄어들다" }, { english: "diplomat", korean: "외교관" }, { english: "discrimination", korean: "차별" },
    { english: "dispute", korean: "분쟁" }, { english: "distribute", korean: "분배하다" }, { english: "diverse", korean: "다양한" },
    { english: "dominant", korean: "지배적인" }, { english: "drought", korean: "가뭄" }, { english: "dynamic", korean: "역동적인" },
    { english: "elaborate", korean: "정교한" }, { english: "eliminate", korean: "제거하다" }, { english: "emphasize", korean: "강조하다" },
    { english: "empower", korean: "권한을 부여하다" }, { english: "enforce", korean: "시행하다" }, { english: "enhance", korean: "향상시키다" },
    { english: "ensure", korean: "보장하다" }, { english: "epidemic", korean: "전염병" }, { english: "equality", korean: "평등" },
    { english: "equivalent", korean: "동등한" }, { english: "ethical", korean: "윤리적인" }, { english: "evaluate", korean: "평가하다" },
    { english: "evolve", korean: "진화하다" }, { english: "exclusive", korean: "독점적인" }, { english: "execute", korean: "실행하다" },
    { english: "exhaust", korean: "고갈시키다" }, { english: "explicit", korean: "명확한" }, { english: "exploit", korean: "착취하다" },
    { english: "facilitate", korean: "촉진하다" }, { english: "feasible", korean: "실현 가능한" }, { english: "flaw", korean: "결함" },
    { english: "flexible", korean: "유연한" }, { english: "flourish", korean: "번성하다" }, { english: "formulate", korean: "공식화하다" },
    { english: "foster", korean: "육성하다" }, { english: "foundation", korean: "기초" }, { english: "fragile", korean: "취약한" },
    { english: "fraud", korean: "사기" }, { english: "fundamental", korean: "근본적인" }, { english: "generate", korean: "발생시키다" },
    { english: "genuine", korean: "진정한" }, { english: "gradual", korean: "점진적인" }, { english: "gravity", korean: "중력" },
    { english: "hierarchy", korean: "계층 구조" }, { english: "hypothesis", korean: "가설" }, { english: "identical", korean: "동일한" },
    { english: "ideology", korean: "이데올로기" }, { english: "illusion", korean: "환상" }, { english: "implement", korean: "시행하다" },
    { english: "implicit", korean: "암묵적인" }, { english: "indispensable", korean: "필수적인" }, { english: "inequality", korean: "불평등" },
    { english: "inevitable", korean: "불가피한" }, { english: "infrastructure", korean: "인프라" }, { english: "inherent", korean: "고유한" },
    { english: "initiative", korean: "주도권" }, { english: "innovation", korean: "혁신" }, { english: "integrate", korean: "통합하다" },
    { english: "integrity", korean: "진실성" }, { english: "intellectual", korean: "지적인" }, { english: "intend", korean: "의도하다" },
    { english: "interpret", korean: "해석하다" }, { english: "intervene", korean: "개입하다" }, { english: "invest", korean: "투자하다" },
    { english: "justify", korean: "정당화하다" }, { english: "legislation", korean: "법률" }, { english: "legitimate", korean: "합법적인" },
    { english: "liable", korean: "책임이 있는" }, { english: "liberty", korean: "자유" }, { english: "logical", korean: "논리적인" },
    { english: "manipulate", korean: "조작하다" }, { english: "mechanism", korean: "메커니즘" }, { english: "mediate", korean: "조정하다" },
    { english: "minimize", korean: "최소화하다" }, { english: "moderate", korean: "온건한" }, { english: "momentum", korean: "추진력" },
    { english: "monitor", korean: "감시하다" }, { english: "motivate", korean: "동기를 부여하다" }, { english: "mutual", korean: "상호의" },
    { english: "narrative", korean: "서술" }, { english: "neutral", korean: "중립적인" }, { english: "numerous", korean: "다수의" },
    { english: "obligation", korean: "의무" }, { english: "obtain", korean: "얻다" }, { english: "oppose", korean: "반대하다" },
    { english: "optimistic", korean: "낙관적인" }, { english: "outcome", korean: "결과" }, { english: "overwhelm", korean: "압도하다" },
    { english: "perceive", korean: "인식하다" }, { english: "persistent", korean: "지속적인" }, { english: "perspective", korean: "관점" },
    { english: "phenomenon", korean: "현상" }, { english: "philosophy", korean: "철학" }, { english: "potential", korean: "잠재력" },
    { english: "precisely", korean: "정확하게" }, { english: "preliminary", korean: "예비의" }, { english: "prestigious", korean: "명망 있는" },
    { english: "principle", korean: "원칙" }, { english: "privilege", korean: "특권" }, { english: "profound", korean: "심오한" },
    { english: "propaganda", korean: "선전" }, { english: "prospect", korean: "전망" }, { english: "pursuit", korean: "추구" },
    { english: "radical", korean: "급진적인" }, { english: "rationale", korean: "근거" }, { english: "realistic", korean: "현실적인" },
    { english: "recognize", korean: "인식하다" }, { english: "reform", korean: "개혁하다" }, { english: "reinforce", korean: "강화하다" },
    { english: "relevant", korean: "관련 있는" }, { english: "reluctant", korean: "내키지 않는" }, { english: "remarkable", korean: "놀라운" },
    { english: "resolve", korean: "해결하다" }, { english: "restrain", korean: "억제하다" }, { english: "retain", korean: "유지하다" },
    { english: "reveal", korean: "드러내다" }, { english: "rhetoric", korean: "수사법" }, { english: "rigorous", korean: "엄격한" },
    { english: "robust", korean: "강건한" }, { english: "sacrifice", korean: "희생하다" }, { english: "scholar", korean: "학자" },
    { english: "scrutiny", korean: "면밀한 검토" }, { english: "significant", korean: "중요한" }, { english: "simultaneously", korean: "동시에" },
    { english: "sophisticated", korean: "정교한" }, { english: "sovereign", korean: "주권의" }, { english: "specific", korean: "구체적인" },
    { english: "speculation", korean: "추측" }, { english: "stable", korean: "안정적인" }, { english: "statistics", korean: "통계" },
    { english: "stereotype", korean: "고정관념" }, { english: "stimulus", korean: "자극" }, { english: "subordinate", korean: "하위의" },
    { english: "subsequent", korean: "그 다음의" }, { english: "substantial", korean: "상당한" }, { english: "subtle", korean: "미묘한" },
    { english: "sufficient", korean: "충분한" }, { english: "suppress", korean: "억압하다" }, { english: "sustainable", korean: "지속 가능한" },
    { english: "thorough", korean: "철저한" }, { english: "tolerance", korean: "관용" }, { english: "transparent", korean: "투명한" },
    { english: "ultimate", korean: "궁극적인" }, { english: "undermine", korean: "약화시키다" }, { english: "unique", korean: "독특한" },
    { english: "universal", korean: "보편적인" }, { english: "unprecedented", korean: "전례 없는" }, { english: "utilize", korean: "활용하다" },
    { english: "valid", korean: "유효한" }, { english: "verify", korean: "확인하다" }, { english: "virtually", korean: "사실상" },
    { english: "vision", korean: "비전" }, { english: "vital", korean: "필수적인" }, { english: "vulnerable", korean: "취약한" },
    { english: "widespread", korean: "광범위한" }, { english: "yield", korean: "산출하다" },
  ],
};

export async function POST(req: Request) {
  const tid = await getTeacherId(req);
  if (!tid) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const results: Record<string, string> = {};

  for (const [gradeName, words] of Object.entries(MIDDLE_WORDS)) {
    let wordSet = await prisma.wordSet.findFirst({ where: { name: gradeName } });

    if (!wordSet) {
      const order = gradeName === "중1" ? 7 : gradeName === "중2" ? 8 : 9;
      const emoji = gradeName === "중1" ? "📗" : gradeName === "중2" ? "📘" : "📙";
      wordSet = await prisma.wordSet.create({
        data: { name: gradeName, description: `중학교 ${gradeName.replace("중", "")}학년`, emoji, order },
      });
    }

    const existing = await prisma.word.count({ where: { wordSetId: wordSet.id } });
    if (existing > 0) {
      results[gradeName] = `이미 ${existing}개 단어 존재 (스킵)`;
      continue;
    }

    await prisma.word.createMany({
      data: words.map((w, i) => ({ wordSetId: wordSet!.id, english: w.english, korean: w.korean, order: i + 1 })),
    });
    results[gradeName] = `${words.length}개 단어 추가 완료`;
  }

  return NextResponse.json({ ok: true, results });
}
