import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const WORD_SETS = [
  {
    name: "3학년",
    emoji: "🌱",
    description: "초등 3학년 영어 기초 어휘",
    words: [
      // 숫자
      { english: "one", korean: "1, 하나" },
      { english: "two", korean: "2, 둘" },
      { english: "three", korean: "3, 셋" },
      { english: "four", korean: "4, 넷" },
      { english: "five", korean: "5, 다섯" },
      { english: "six", korean: "6, 여섯" },
      { english: "seven", korean: "7, 일곱" },
      { english: "eight", korean: "8, 여덟" },
      { english: "nine", korean: "9, 아홉" },
      { english: "ten", korean: "10, 열" },
      { english: "eleven", korean: "11, 열하나" },
      { english: "twelve", korean: "12, 열둘" },
      { english: "twenty", korean: "20, 스물" },
      { english: "thirty", korean: "30, 서른" },
      { english: "hundred", korean: "100, 백" },
      // 색깔
      { english: "red", korean: "빨간색" },
      { english: "blue", korean: "파란색" },
      { english: "green", korean: "초록색" },
      { english: "yellow", korean: "노란색" },
      { english: "white", korean: "흰색" },
      { english: "black", korean: "검은색" },
      { english: "pink", korean: "분홍색" },
      { english: "purple", korean: "보라색" },
      { english: "orange", korean: "주황색" },
      { english: "brown", korean: "갈색" },
      { english: "gray", korean: "회색" },
      // 과일
      { english: "apple", korean: "사과" },
      { english: "banana", korean: "바나나" },
      { english: "grape", korean: "포도" },
      { english: "strawberry", korean: "딸기" },
      { english: "watermelon", korean: "수박" },
      { english: "pineapple", korean: "파인애플" },
      { english: "peach", korean: "복숭아" },
      { english: "pear", korean: "배" },
      { english: "cherry", korean: "체리" },
      { english: "mango", korean: "망고" },
      { english: "lemon", korean: "레몬" },
      { english: "melon", korean: "멜론" },
      // 채소
      { english: "carrot", korean: "당근" },
      { english: "potato", korean: "감자" },
      { english: "tomato", korean: "토마토" },
      { english: "onion", korean: "양파" },
      { english: "cucumber", korean: "오이" },
      { english: "cabbage", korean: "양배추" },
      { english: "corn", korean: "옥수수" },
      { english: "mushroom", korean: "버섯" },
      { english: "broccoli", korean: "브로콜리" },
      { english: "lettuce", korean: "상추" },
      // 동물
      { english: "dog", korean: "강아지" },
      { english: "cat", korean: "고양이" },
      { english: "rabbit", korean: "토끼" },
      { english: "bear", korean: "곰" },
      { english: "elephant", korean: "코끼리" },
      { english: "lion", korean: "사자" },
      { english: "tiger", korean: "호랑이" },
      { english: "penguin", korean: "펭귄" },
      { english: "monkey", korean: "원숭이" },
      { english: "fish", korean: "물고기" },
      { english: "bird", korean: "새" },
      { english: "horse", korean: "말" },
      { english: "cow", korean: "소" },
      { english: "pig", korean: "돼지" },
      { english: "sheep", korean: "양" },
      { english: "duck", korean: "오리" },
      { english: "chicken", korean: "닭" },
      { english: "frog", korean: "개구리" },
      { english: "snake", korean: "뱀" },
      { english: "turtle", korean: "거북이" },
      // 가족
      { english: "mom", korean: "엄마" },
      { english: "dad", korean: "아빠" },
      { english: "brother", korean: "형/남동생" },
      { english: "sister", korean: "언니/여동생" },
      { english: "grandfather", korean: "할아버지" },
      { english: "grandmother", korean: "할머니" },
      { english: "uncle", korean: "삼촌/외삼촌" },
      { english: "aunt", korean: "이모/고모" },
      { english: "baby", korean: "아기" },
      { english: "family", korean: "가족" },
      // 신체
      { english: "head", korean: "머리" },
      { english: "eye", korean: "눈" },
      { english: "ear", korean: "귀" },
      { english: "nose", korean: "코" },
      { english: "mouth", korean: "입" },
      { english: "hand", korean: "손" },
      { english: "foot", korean: "발" },
      { english: "leg", korean: "다리" },
      { english: "arm", korean: "팔" },
      { english: "hair", korean: "머리카락" },
      { english: "face", korean: "얼굴" },
      { english: "finger", korean: "손가락" },
      { english: "shoulder", korean: "어깨" },
      { english: "knee", korean: "무릎" },
      { english: "stomach", korean: "배" },
      { english: "back", korean: "등" },
      // 날씨
      { english: "sunny", korean: "맑은" },
      { english: "cloudy", korean: "흐린" },
      { english: "rainy", korean: "비 오는" },
      { english: "windy", korean: "바람 부는" },
      { english: "snowy", korean: "눈 오는" },
      { english: "hot", korean: "더운" },
      { english: "cold", korean: "추운" },
      { english: "warm", korean: "따뜻한" },
      { english: "cool", korean: "시원한" },
      // 학용품
      { english: "book", korean: "책" },
      { english: "pencil", korean: "연필" },
      { english: "eraser", korean: "지우개" },
      { english: "ruler", korean: "자" },
      { english: "bag", korean: "가방" },
      { english: "notebook", korean: "공책" },
      { english: "pen", korean: "펜" },
      { english: "crayon", korean: "크레용" },
      { english: "scissors", korean: "가위" },
      { english: "glue", korean: "풀" },
      // 기초 인사/표현
      { english: "hello", korean: "안녕" },
      { english: "goodbye", korean: "안녕히 가세요" },
      { english: "please", korean: "제발, 부탁해요" },
      { english: "thank you", korean: "감사합니다" },
      { english: "sorry", korean: "미안해요" },
      { english: "yes", korean: "네" },
      { english: "no", korean: "아니요" },
      { english: "help", korean: "도움, 도와주세요" },
      { english: "name", korean: "이름" },
      { english: "age", korean: "나이" },
      // 기초 동사
      { english: "go", korean: "가다" },
      { english: "come", korean: "오다" },
      { english: "eat", korean: "먹다" },
      { english: "drink", korean: "마시다" },
      { english: "sleep", korean: "자다" },
      { english: "play", korean: "놀다" },
      { english: "run", korean: "달리다" },
      { english: "jump", korean: "점프하다" },
      { english: "sit", korean: "앉다" },
      { english: "stand", korean: "서다" },
      { english: "walk", korean: "걷다" },
      { english: "like", korean: "좋아하다" },
      { english: "love", korean: "사랑하다" },
      { english: "have", korean: "가지다" },
      { english: "see", korean: "보다" },
      // 기초 형용사
      { english: "big", korean: "큰" },
      { english: "small", korean: "작은" },
      { english: "tall", korean: "키가 큰" },
      { english: "short", korean: "짧은, 키가 작은" },
      { english: "long", korean: "긴" },
      { english: "new", korean: "새로운" },
      { english: "old", korean: "오래된, 늙은" },
      { english: "good", korean: "좋은" },
      { english: "bad", korean: "나쁜" },
      { english: "happy", korean: "행복한" },
      { english: "sad", korean: "슬픈" },
      { english: "fast", korean: "빠른" },
      { english: "slow", korean: "느린" },
      { english: "pretty", korean: "예쁜" },
      { english: "cute", korean: "귀여운" },
      // 장소
      { english: "school", korean: "학교" },
      { english: "home", korean: "집" },
      { english: "park", korean: "공원" },
      { english: "hospital", korean: "병원" },
      { english: "library", korean: "도서관" },
      { english: "store", korean: "가게" },
      { english: "restaurant", korean: "식당" },
      { english: "zoo", korean: "동물원" },
      { english: "church", korean: "교회" },
      { english: "market", korean: "시장" },
      // 요일
      { english: "Monday", korean: "월요일" },
      { english: "Tuesday", korean: "화요일" },
      { english: "Wednesday", korean: "수요일" },
      { english: "Thursday", korean: "목요일" },
      { english: "Friday", korean: "금요일" },
      { english: "Saturday", korean: "토요일" },
      { english: "Sunday", korean: "일요일" },
      // 계절/시간
      { english: "spring", korean: "봄" },
      { english: "summer", korean: "여름" },
      { english: "autumn", korean: "가을" },
      { english: "winter", korean: "겨울" },
      { english: "today", korean: "오늘" },
      { english: "tomorrow", korean: "내일" },
      { english: "yesterday", korean: "어제" },
      { english: "morning", korean: "아침" },
      { english: "afternoon", korean: "오후" },
      { english: "evening", korean: "저녁" },
      { english: "night", korean: "밤" },
      // 기초 명사
      { english: "water", korean: "물" },
      { english: "food", korean: "음식" },
      { english: "friend", korean: "친구" },
      { english: "teacher", korean: "선생님" },
      { english: "student", korean: "학생" },
      { english: "desk", korean: "책상" },
      { english: "chair", korean: "의자" },
      { english: "door", korean: "문" },
      { english: "window", korean: "창문" },
      { english: "ball", korean: "공" },
      // 추가 단어
      { english: "cat", korean: "고양이" },
      { english: "flower", korean: "꽃" },
      { english: "tree", korean: "나무" },
      { english: "grass", korean: "풀" },
      { english: "rock", korean: "돌" },
      { english: "sand", korean: "모래" },
      { english: "ice", korean: "얼음" },
      { english: "fire", korean: "불" },
      { english: "earth", korean: "땅, 지구" },
      { english: "air", korean: "공기" },
      { english: "hat", korean: "모자" },
      { english: "cup", korean: "컵" },
      { english: "spoon", korean: "숟가락" },
      { english: "fork", korean: "포크" },
      { english: "knife", korean: "칼" },
      { english: "plate", korean: "접시" },
      { english: "box", korean: "상자" },
      { english: "bag", korean: "가방" },
      { english: "toy", korean: "장난감" },
      { english: "doll", korean: "인형" },
      { english: "game", korean: "게임" },
      { english: "song", korean: "노래" },
      { english: "story", korean: "이야기" },
      { english: "picture", korean: "그림, 사진" },
      { english: "color", korean: "색" },
      { english: "shape", korean: "모양" },
      { english: "circle", korean: "원" },
      { english: "square", korean: "정사각형" },
      { english: "triangle", korean: "삼각형" },
      { english: "star", korean: "별" },
      { english: "heart", korean: "하트, 심장" },
      { english: "right", korean: "오른쪽, 맞는" },
      { english: "left", korean: "왼쪽" },
      { english: "up", korean: "위" },
      { english: "down", korean: "아래" },
      { english: "in", korean: "안에" },
      { english: "out", korean: "밖에" },
      { english: "over", korean: "위에" },
      { english: "under", korean: "아래에" },
      { english: "near", korean: "가까운" },
      { english: "far", korean: "먼" },
      { english: "here", korean: "여기" },
      { english: "there", korean: "거기" },
      { english: "where", korean: "어디" },
      { english: "when", korean: "언제" },
      { english: "what", korean: "무엇" },
      { english: "who", korean: "누구" },
      { english: "why", korean: "왜" },
      { english: "how", korean: "어떻게" },
      { english: "sweet", korean: "달콤한" },
      { english: "salty", korean: "짠" },
      { english: "fresh", korean: "신선한" },
      { english: "soft", korean: "부드러운" },
      { english: "hard", korean: "딱딱한" },
      { english: "rough", korean: "거친" },
      { english: "smooth", korean: "매끄러운" },
      { english: "wet", korean: "젖은" },
      { english: "dry", korean: "건조한" },
      { english: "full", korean: "가득 찬" },
      { english: "empty", korean: "빈" },
    ],
  },
  {
    name: "4학년",
    emoji: "🌿",
    description: "초등 4학년 영어 생활 어휘",
    words: [
      // 음식
      { english: "pizza", korean: "피자" },
      { english: "hamburger", korean: "햄버거" },
      { english: "sandwich", korean: "샌드위치" },
      { english: "noodle", korean: "국수, 면" },
      { english: "rice", korean: "밥, 쌀" },
      { english: "bread", korean: "빵" },
      { english: "cake", korean: "케이크" },
      { english: "cookie", korean: "쿠키" },
      { english: "ice cream", korean: "아이스크림" },
      { english: "juice", korean: "주스" },
      { english: "milk", korean: "우유" },
      { english: "tea", korean: "차" },
      { english: "egg", korean: "달걀" },
      { english: "soup", korean: "국, 수프" },
      { english: "salad", korean: "샐러드" },
      { english: "steak", korean: "스테이크" },
      { english: "fried", korean: "튀긴" },
      { english: "sweet", korean: "달콤한" },
      { english: "sour", korean: "신" },
      { english: "spicy", korean: "매운" },
      // 직업
      { english: "doctor", korean: "의사" },
      { english: "nurse", korean: "간호사" },
      { english: "police officer", korean: "경찰관" },
      { english: "firefighter", korean: "소방관" },
      { english: "cook", korean: "요리사" },
      { english: "farmer", korean: "농부" },
      { english: "pilot", korean: "조종사" },
      { english: "singer", korean: "가수" },
      { english: "actor", korean: "배우" },
      { english: "artist", korean: "예술가" },
      { english: "driver", korean: "운전사" },
      { english: "engineer", korean: "엔지니어" },
      { english: "scientist", korean: "과학자" },
      { english: "soldier", korean: "군인" },
      { english: "baker", korean: "제빵사" },
      // 교통수단
      { english: "bus", korean: "버스" },
      { english: "car", korean: "자동차" },
      { english: "train", korean: "기차" },
      { english: "airplane", korean: "비행기" },
      { english: "bicycle", korean: "자전거" },
      { english: "boat", korean: "배" },
      { english: "ship", korean: "배, 선박" },
      { english: "taxi", korean: "택시" },
      { english: "subway", korean: "지하철" },
      { english: "helicopter", korean: "헬리콥터" },
      { english: "truck", korean: "트럭" },
      { english: "motorcycle", korean: "오토바이" },
      { english: "rocket", korean: "로켓" },
      // 집/가구
      { english: "house", korean: "집" },
      { english: "kitchen", korean: "부엌" },
      { english: "bathroom", korean: "욕실" },
      { english: "bedroom", korean: "침실" },
      { english: "living room", korean: "거실" },
      { english: "table", korean: "탁자" },
      { english: "bed", korean: "침대" },
      { english: "sofa", korean: "소파" },
      { english: "lamp", korean: "램프, 전등" },
      { english: "clock", korean: "시계" },
      { english: "refrigerator", korean: "냉장고" },
      { english: "television", korean: "텔레비전" },
      { english: "computer", korean: "컴퓨터" },
      { english: "phone", korean: "전화기" },
      { english: "mirror", korean: "거울" },
      // 옷
      { english: "shirt", korean: "셔츠" },
      { english: "pants", korean: "바지" },
      { english: "skirt", korean: "치마" },
      { english: "dress", korean: "원피스" },
      { english: "shoes", korean: "신발" },
      { english: "hat", korean: "모자" },
      { english: "coat", korean: "코트" },
      { english: "jacket", korean: "재킷" },
      { english: "socks", korean: "양말" },
      { english: "gloves", korean: "장갑" },
      { english: "scarf", korean: "목도리" },
      { english: "uniform", korean: "교복, 유니폼" },
      { english: "jeans", korean: "청바지" },
      { english: "boots", korean: "부츠" },
      { english: "sneakers", korean: "운동화" },
      // 월
      { english: "January", korean: "1월" },
      { english: "February", korean: "2월" },
      { english: "March", korean: "3월" },
      { english: "April", korean: "4월" },
      { english: "May", korean: "5월" },
      { english: "June", korean: "6월" },
      { english: "July", korean: "7월" },
      { english: "August", korean: "8월" },
      { english: "September", korean: "9월" },
      { english: "October", korean: "10월" },
      { english: "November", korean: "11월" },
      { english: "December", korean: "12월" },
      // 시간 표현
      { english: "week", korean: "주" },
      { english: "month", korean: "달, 월" },
      { english: "year", korean: "해, 년" },
      { english: "hour", korean: "시간" },
      { english: "minute", korean: "분" },
      { english: "second", korean: "초" },
      { english: "early", korean: "일찍" },
      { english: "late", korean: "늦은" },
      // 동사
      { english: "read", korean: "읽다" },
      { english: "write", korean: "쓰다" },
      { english: "study", korean: "공부하다" },
      { english: "draw", korean: "그리다" },
      { english: "sing", korean: "노래하다" },
      { english: "dance", korean: "춤추다" },
      { english: "swim", korean: "수영하다" },
      { english: "ride", korean: "타다" },
      { english: "fly", korean: "날다" },
      { english: "drive", korean: "운전하다" },
      { english: "cook", korean: "요리하다" },
      { english: "clean", korean: "청소하다" },
      { english: "wash", korean: "씻다" },
      { english: "open", korean: "열다" },
      { english: "close", korean: "닫다" },
      { english: "buy", korean: "사다" },
      { english: "sell", korean: "팔다" },
      { english: "find", korean: "찾다" },
      { english: "lose", korean: "잃다" },
      { english: "know", korean: "알다" },
      { english: "think", korean: "생각하다" },
      { english: "say", korean: "말하다" },
      { english: "ask", korean: "묻다" },
      { english: "answer", korean: "대답하다" },
      { english: "start", korean: "시작하다" },
      { english: "stop", korean: "멈추다" },
      { english: "wait", korean: "기다리다" },
      { english: "try", korean: "시도하다" },
      { english: "listen", korean: "듣다" },
      { english: "watch", korean: "보다, 지켜보다" },
      // 형용사
      { english: "tired", korean: "피곤한" },
      { english: "hungry", korean: "배고픈" },
      { english: "thirsty", korean: "목마른" },
      { english: "sick", korean: "아픈" },
      { english: "busy", korean: "바쁜" },
      { english: "easy", korean: "쉬운" },
      { english: "hard", korean: "어려운, 딱딱한" },
      { english: "light", korean: "가벼운, 밝은" },
      { english: "heavy", korean: "무거운" },
      { english: "clean", korean: "깨끗한" },
      { english: "dirty", korean: "더러운" },
      { english: "loud", korean: "시끄러운" },
      { english: "quiet", korean: "조용한" },
      { english: "safe", korean: "안전한" },
      { english: "important", korean: "중요한" },
      // 순서/수량
      { english: "first", korean: "첫 번째" },
      { english: "second", korean: "두 번째" },
      { english: "third", korean: "세 번째" },
      { english: "last", korean: "마지막" },
      { english: "next", korean: "다음" },
      { english: "many", korean: "많은" },
      { english: "few", korean: "적은" },
      { english: "all", korean: "모든" },
      { english: "some", korean: "몇몇의" },
      { english: "half", korean: "절반" },
      // 장소
      { english: "airport", korean: "공항" },
      { english: "station", korean: "역" },
      { english: "bank", korean: "은행" },
      { english: "post office", korean: "우체국" },
      { english: "hotel", korean: "호텔" },
      { english: "theater", korean: "극장" },
      { english: "museum", korean: "박물관" },
      { english: "stadium", korean: "경기장" },
      { english: "supermarket", korean: "슈퍼마켓" },
      { english: "pharmacy", korean: "약국" },
      // 추가 단어
      { english: "church", korean: "교회" },
      { english: "temple", korean: "절, 사원" },
      { english: "palace", korean: "궁전" },
      { english: "castle", korean: "성" },
      { english: "bridge", korean: "다리" },
      { english: "road", korean: "도로" },
      { english: "street", korean: "거리" },
      { english: "corner", korean: "모퉁이" },
      { english: "sign", korean: "표지판" },
      { english: "light", korean: "빛, 신호등" },
      { english: "umbrella", korean: "우산" },
      { english: "mirror", korean: "거울" },
      { english: "camera", korean: "카메라" },
      { english: "radio", korean: "라디오" },
      { english: "newspaper", korean: "신문" },
      { english: "magazine", korean: "잡지" },
      { english: "letter", korean: "편지" },
      { english: "stamp", korean: "우표" },
      { english: "envelope", korean: "봉투" },
      { english: "calendar", korean: "달력" },
      { english: "schedule", korean: "일정" },
      { english: "ticket", korean: "티켓" },
      { english: "map", korean: "지도" },
      { english: "key", korean: "열쇠" },
      { english: "wallet", korean: "지갑" },
      { english: "money", korean: "돈" },
      { english: "coin", korean: "동전" },
      { english: "price", korean: "가격" },
      { english: "change", korean: "잔돈, 변화" },
      { english: "receipt", korean: "영수증" },
      { english: "order", korean: "주문" },
      { english: "menu", korean: "메뉴" },
      { english: "tip", korean: "팁" },
      { english: "bill", korean: "계산서" },
      { english: "glass", korean: "유리, 컵" },
      { english: "bottle", korean: "병" },
      { english: "can", korean: "캔" },
      { english: "bag", korean: "봉지" },
      { english: "package", korean: "포장, 소포" },
      { english: "gift", korean: "선물" },
      { english: "card", korean: "카드" },
      { english: "flower", korean: "꽃" },
      { english: "candle", korean: "초" },
      { english: "balloon", korean: "풍선" },
      { english: "party", korean: "파티" },
      { english: "birthday", korean: "생일" },
      { english: "holiday", korean: "휴일" },
      { english: "vacation", korean: "방학, 휴가" },
      { english: "trip", korean: "여행" },
      { english: "tour", korean: "투어" },
      { english: "guide", korean: "안내원, 안내하다" },
      { english: "souvenir", korean: "기념품" },
      { english: "passport", korean: "여권" },
      { english: "culture", korean: "문화" },
      { english: "custom", korean: "풍습" },
      { english: "tradition", korean: "전통" },
      { english: "language", korean: "언어" },
      { english: "translate", korean: "번역하다" },
      { english: "foreign", korean: "외국의" },
      { english: "abroad", korean: "해외에" },
      { english: "international", korean: "국제적인" },
      { english: "world", korean: "세계" },
      { english: "country", korean: "나라" },
      { english: "capital", korean: "수도" },
      { english: "flag", korean: "국기" },
      { english: "nation", korean: "국가" },
      { english: "people", korean: "사람들" },
      { english: "population", korean: "인구" },
      { english: "citizen", korean: "시민" },
      { english: "vote", korean: "투표하다" },
      { english: "rule", korean: "규칙" },
      { english: "leader", korean: "지도자" },
      { english: "president", korean: "대통령" },
      { english: "king", korean: "왕" },
      { english: "queen", korean: "여왕" },
      { english: "history", korean: "역사" },
      { english: "future", korean: "미래" },
      { english: "past", korean: "과거" },
      { english: "present", korean: "현재, 선물" },
    ],
  },
  {
    name: "5학년",
    emoji: "🌳",
    description: "초등 5학년 영어 확장 어휘",
    words: [
      // 스포츠
      { english: "soccer", korean: "축구" },
      { english: "basketball", korean: "농구" },
      { english: "baseball", korean: "야구" },
      { english: "tennis", korean: "테니스" },
      { english: "swimming", korean: "수영" },
      { english: "running", korean: "달리기" },
      { english: "cycling", korean: "자전거 타기" },
      { english: "skiing", korean: "스키" },
      { english: "skating", korean: "스케이팅" },
      { english: "golf", korean: "골프" },
      { english: "volleyball", korean: "배구" },
      { english: "badminton", korean: "배드민턴" },
      { english: "taekwondo", korean: "태권도" },
      { english: "gymnastics", korean: "체조" },
      { english: "marathon", korean: "마라톤" },
      // 취미
      { english: "painting", korean: "그림 그리기" },
      { english: "gardening", korean: "정원 가꾸기" },
      { english: "hiking", korean: "등산" },
      { english: "camping", korean: "캠핑" },
      { english: "fishing", korean: "낚시" },
      { english: "photography", korean: "사진 촬영" },
      { english: "collecting", korean: "수집하기" },
      { english: "crafts", korean: "공예" },
      { english: "traveling", korean: "여행" },
      { english: "shopping", korean: "쇼핑" },
      // 자연
      { english: "mountain", korean: "산" },
      { english: "river", korean: "강" },
      { english: "lake", korean: "호수" },
      { english: "sea", korean: "바다" },
      { english: "ocean", korean: "대양" },
      { english: "island", korean: "섬" },
      { english: "forest", korean: "숲" },
      { english: "desert", korean: "사막" },
      { english: "beach", korean: "해변" },
      { english: "sky", korean: "하늘" },
      { english: "cloud", korean: "구름" },
      { english: "sun", korean: "태양" },
      { english: "moon", korean: "달" },
      { english: "star", korean: "별" },
      { english: "rain", korean: "비" },
      { english: "snow", korean: "눈" },
      { english: "wind", korean: "바람" },
      { english: "thunder", korean: "천둥" },
      { english: "lightning", korean: "번개" },
      { english: "rainbow", korean: "무지개" },
      { english: "waterfall", korean: "폭포" },
      { english: "valley", korean: "계곡" },
      { english: "cave", korean: "동굴" },
      { english: "volcano", korean: "화산" },
      { english: "earthquake", korean: "지진" },
      // 감정
      { english: "excited", korean: "신이 난" },
      { english: "scared", korean: "무서운" },
      { english: "surprised", korean: "놀란" },
      { english: "worried", korean: "걱정하는" },
      { english: "bored", korean: "지루한" },
      { english: "nervous", korean: "긴장한" },
      { english: "proud", korean: "자랑스러운" },
      { english: "lonely", korean: "외로운" },
      { english: "confused", korean: "혼란스러운" },
      { english: "disappointed", korean: "실망한" },
      { english: "grateful", korean: "감사한" },
      { english: "hopeful", korean: "희망찬" },
      { english: "curious", korean: "호기심 있는" },
      { english: "calm", korean: "차분한" },
      { english: "angry", korean: "화난" },
      // 학교 과목/생활
      { english: "math", korean: "수학" },
      { english: "science", korean: "과학" },
      { english: "history", korean: "역사" },
      { english: "English", korean: "영어" },
      { english: "art", korean: "미술" },
      { english: "music", korean: "음악" },
      { english: "gym", korean: "체육관" },
      { english: "cafeteria", korean: "식당, 구내식당" },
      { english: "playground", korean: "운동장" },
      { english: "classroom", korean: "교실" },
      { english: "lesson", korean: "수업" },
      { english: "homework", korean: "숙제" },
      { english: "exam", korean: "시험" },
      { english: "grade", korean: "학년, 성적" },
      { english: "subject", korean: "과목" },
      // 동사 심화
      { english: "understand", korean: "이해하다" },
      { english: "remember", korean: "기억하다" },
      { english: "forget", korean: "잊다" },
      { english: "believe", korean: "믿다" },
      { english: "decide", korean: "결정하다" },
      { english: "choose", korean: "선택하다" },
      { english: "plan", korean: "계획하다" },
      { english: "practice", korean: "연습하다" },
      { english: "prepare", korean: "준비하다" },
      { english: "improve", korean: "향상시키다" },
      { english: "enjoy", korean: "즐기다" },
      { english: "prefer", korean: "선호하다" },
      { english: "hope", korean: "바라다" },
      { english: "wish", korean: "소원하다" },
      { english: "promise", korean: "약속하다" },
      { english: "suggest", korean: "제안하다" },
      { english: "recommend", korean: "추천하다" },
      { english: "agree", korean: "동의하다" },
      { english: "disagree", korean: "반대하다" },
      { english: "explain", korean: "설명하다" },
      // 형용사 심화
      { english: "beautiful", korean: "아름다운" },
      { english: "wonderful", korean: "훌륭한" },
      { english: "terrible", korean: "끔찍한" },
      { english: "amazing", korean: "놀라운" },
      { english: "interesting", korean: "흥미로운" },
      { english: "boring", korean: "지루한" },
      { english: "delicious", korean: "맛있는" },
      { english: "fantastic", korean: "환상적인" },
      { english: "perfect", korean: "완벽한" },
      { english: "popular", korean: "인기 있는" },
      { english: "famous", korean: "유명한" },
      { english: "smart", korean: "똑똑한" },
      { english: "clever", korean: "영리한" },
      { english: "brave", korean: "용감한" },
      { english: "kind", korean: "친절한" },
      { english: "gentle", korean: "온화한" },
      { english: "polite", korean: "예의 바른" },
      { english: "honest", korean: "정직한" },
      { english: "funny", korean: "재미있는" },
      { english: "serious", korean: "진지한" },
      // 접속사/전치사
      { english: "because", korean: "왜냐하면" },
      { english: "although", korean: "비록 ~이지만" },
      { english: "however", korean: "그러나" },
      { english: "therefore", korean: "그러므로" },
      { english: "during", korean: "~동안" },
      { english: "until", korean: "~까지" },
      { english: "since", korean: "~이후로" },
      { english: "between", korean: "~사이에" },
      { english: "among", korean: "~중에서" },
      { english: "without", korean: "~없이" },
      // 동물 추가
      { english: "giraffe", korean: "기린" },
      { english: "zebra", korean: "얼룩말" },
      { english: "crocodile", korean: "악어" },
      { english: "dolphin", korean: "돌고래" },
      { english: "whale", korean: "고래" },
      { english: "shark", korean: "상어" },
      { english: "eagle", korean: "독수리" },
      { english: "parrot", korean: "앵무새" },
      { english: "butterfly", korean: "나비" },
      { english: "bee", korean: "벌" },
      // 신체/건강
      { english: "heart", korean: "심장" },
      { english: "brain", korean: "뇌" },
      { english: "blood", korean: "피" },
      { english: "bone", korean: "뼈" },
      { english: "muscle", korean: "근육" },
      { english: "healthy", korean: "건강한" },
      { english: "exercise", korean: "운동" },
      { english: "medicine", korean: "약" },
      { english: "fever", korean: "열" },
      { english: "headache", korean: "두통" },
      // 기타 명사
      { english: "gift", korean: "선물" },
      { english: "letter", korean: "편지" },
      { english: "address", korean: "주소" },
      { english: "ticket", korean: "표, 티켓" },
      { english: "map", korean: "지도" },
      { english: "camera", korean: "카메라" },
      { english: "umbrella", korean: "우산" },
      { english: "key", korean: "열쇠" },
      { english: "money", korean: "돈" },
      { english: "price", korean: "가격" },
      // 추가 단어
      { english: "insect", korean: "곤충" },
      { english: "ant", korean: "개미" },
      { english: "spider", korean: "거미" },
      { english: "fly", korean: "파리" },
      { english: "mosquito", korean: "모기" },
      { english: "ladybug", korean: "무당벌레" },
      { english: "dragonfly", korean: "잠자리" },
      { english: "worm", korean: "벌레" },
      { english: "seed", korean: "씨앗" },
      { english: "leaf", korean: "나뭇잎" },
      { english: "branch", korean: "나뭇가지" },
      { english: "root", korean: "뿌리" },
      { english: "soil", korean: "흙" },
      { english: "pond", korean: "연못" },
      { english: "stream", korean: "개울" },
      { english: "hill", korean: "언덕" },
      { english: "field", korean: "들판" },
      { english: "farm", korean: "농장" },
      { english: "garden", korean: "정원" },
      { english: "fence", korean: "울타리" },
      { english: "path", korean: "길, 경로" },
      { english: "bridge", korean: "다리" },
      { english: "tunnel", korean: "터널" },
      { english: "tower", korean: "탑" },
      { english: "building", korean: "건물" },
      { english: "roof", korean: "지붕" },
      { english: "floor", korean: "바닥, 층" },
      { english: "wall", korean: "벽" },
      { english: "ceiling", korean: "천장" },
      { english: "step", korean: "계단, 발걸음" },
      { english: "hall", korean: "복도, 홀" },
      { english: "garage", korean: "차고" },
      { english: "yard", korean: "마당" },
      { english: "neighbor", korean: "이웃" },
      { english: "village", korean: "마을" },
      { english: "town", korean: "도시, 마을" },
      { english: "city", korean: "도시" },
      { english: "suburb", korean: "교외" },
      { english: "downtown", korean: "시내" },
      { english: "north", korean: "북쪽" },
      { english: "south", korean: "남쪽" },
      { english: "east", korean: "동쪽" },
      { english: "west", korean: "서쪽" },
      { english: "turn", korean: "돌다, 방향을 바꾸다" },
      { english: "straight", korean: "직진, 곧은" },
      { english: "across", korean: "건너서" },
      { english: "along", korean: "~을 따라" },
      { english: "through", korean: "~을 통해" },
      { english: "around", korean: "~주변에" },
      { english: "toward", korean: "~을 향해" },
      { english: "inside", korean: "안쪽에" },
      { english: "outside", korean: "바깥쪽에" },
      { english: "above", korean: "위에" },
      { english: "below", korean: "아래에" },
      { english: "beside", korean: "옆에" },
      { english: "behind", korean: "뒤에" },
      { english: "front", korean: "앞" },
      { english: "middle", korean: "가운데" },
      { english: "center", korean: "중심" },
      { english: "edge", korean: "가장자리" },
      { english: "side", korean: "옆, 측면" },
      { english: "top", korean: "꼭대기" },
      { english: "bottom", korean: "바닥, 맨 아래" },
      { english: "corner", korean: "모퉁이" },
      { english: "area", korean: "지역, 구역" },
      { english: "space", korean: "공간, 우주" },
      { english: "distance", korean: "거리" },
      { english: "size", korean: "크기" },
      { english: "width", korean: "너비" },
      { english: "height", korean: "높이" },
      { english: "depth", korean: "깊이" },
      { english: "weight", korean: "무게" },
      { english: "temperature", korean: "온도" },
      { english: "degree", korean: "도, 정도" },
      { english: "speed", korean: "속도" },
      { english: "direction", korean: "방향" },
      { english: "position", korean: "위치" },
    ],
  },
  {
    name: "6학년",
    emoji: "🌲",
    description: "초등 6학년 영어 심화 어휘",
    words: [
      // 환경
      { english: "environment", korean: "환경" },
      { english: "nature", korean: "자연" },
      { english: "pollution", korean: "오염" },
      { english: "recycle", korean: "재활용하다" },
      { english: "energy", korean: "에너지" },
      { english: "climate", korean: "기후" },
      { english: "global warming", korean: "지구 온난화" },
      { english: "flood", korean: "홍수" },
      { english: "drought", korean: "가뭄" },
      { english: "wildlife", korean: "야생동물" },
      { english: "ecosystem", korean: "생태계" },
      { english: "conservation", korean: "보전" },
      { english: "sustainable", korean: "지속 가능한" },
      { english: "deforestation", korean: "삼림 벌채" },
      { english: "endangered", korean: "멸종 위기의" },
      // 사회/문화
      { english: "culture", korean: "문화" },
      { english: "tradition", korean: "전통" },
      { english: "festival", korean: "축제" },
      { english: "ceremony", korean: "의식, 행사" },
      { english: "custom", korean: "풍습" },
      { english: "language", korean: "언어" },
      { english: "religion", korean: "종교" },
      { english: "government", korean: "정부" },
      { english: "democracy", korean: "민주주의" },
      { english: "law", korean: "법" },
      { english: "freedom", korean: "자유" },
      { english: "peace", korean: "평화" },
      { english: "war", korean: "전쟁" },
      { english: "monument", korean: "기념물" },
      { english: "heritage", korean: "유산" },
      // 건강
      { english: "health", korean: "건강" },
      { english: "nutrition", korean: "영양" },
      { english: "diet", korean: "식단, 다이어트" },
      { english: "disease", korean: "질병" },
      { english: "symptom", korean: "증상" },
      { english: "treatment", korean: "치료" },
      { english: "vaccine", korean: "백신" },
      { english: "allergy", korean: "알레르기" },
      { english: "injury", korean: "부상" },
      { english: "recovery", korean: "회복" },
      { english: "mental", korean: "정신적인" },
      { english: "physical", korean: "신체적인" },
      { english: "stress", korean: "스트레스" },
      { english: "vitamin", korean: "비타민" },
      { english: "dentist", korean: "치과 의사" },
      // 기술
      { english: "technology", korean: "기술" },
      { english: "internet", korean: "인터넷" },
      { english: "smartphone", korean: "스마트폰" },
      { english: "robot", korean: "로봇" },
      { english: "artificial intelligence", korean: "인공지능" },
      { english: "digital", korean: "디지털" },
      { english: "software", korean: "소프트웨어" },
      { english: "program", korean: "프로그램" },
      { english: "application", korean: "앱, 응용 프로그램" },
      { english: "website", korean: "웹사이트" },
      { english: "email", korean: "이메일" },
      { english: "social media", korean: "소셜 미디어" },
      { english: "online", korean: "온라인" },
      { english: "wireless", korean: "무선의" },
      { english: "satellite", korean: "위성" },
      // 직업 심화
      { english: "architect", korean: "건축가" },
      { english: "lawyer", korean: "변호사" },
      { english: "journalist", korean: "기자" },
      { english: "photographer", korean: "사진작가" },
      { english: "designer", korean: "디자이너" },
      { english: "programmer", korean: "프로그래머" },
      { english: "economist", korean: "경제학자" },
      { english: "psychologist", korean: "심리학자" },
      { english: "astronaut", korean: "우주비행사" },
      { english: "veterinarian", korean: "수의사" },
      { english: "pharmacist", korean: "약사" },
      { english: "politician", korean: "정치인" },
      { english: "researcher", korean: "연구원" },
      { english: "diplomat", korean: "외교관" },
      { english: "entrepreneur", korean: "기업가" },
      // 동사 심화
      { english: "achieve", korean: "성취하다" },
      { english: "accomplish", korean: "달성하다" },
      { english: "overcome", korean: "극복하다" },
      { english: "challenge", korean: "도전하다" },
      { english: "develop", korean: "개발하다" },
      { english: "discover", korean: "발견하다" },
      { english: "explore", korean: "탐험하다" },
      { english: "investigate", korean: "조사하다" },
      { english: "analyze", korean: "분석하다" },
      { english: "compare", korean: "비교하다" },
      { english: "evaluate", korean: "평가하다" },
      { english: "communicate", korean: "소통하다" },
      { english: "cooperate", korean: "협력하다" },
      { english: "contribute", korean: "기여하다" },
      { english: "influence", korean: "영향을 미치다" },
      { english: "represent", korean: "대표하다" },
      { english: "describe", korean: "묘사하다" },
      { english: "solve", korean: "해결하다" },
      { english: "create", korean: "창조하다" },
      { english: "protect", korean: "보호하다" },
      // 추상 명사
      { english: "success", korean: "성공" },
      { english: "failure", korean: "실패" },
      { english: "effort", korean: "노력" },
      { english: "courage", korean: "용기" },
      { english: "wisdom", korean: "지혜" },
      { english: "patience", korean: "인내심" },
      { english: "kindness", korean: "친절함" },
      { english: "honesty", korean: "정직함" },
      { english: "responsibility", korean: "책임감" },
      { english: "creativity", korean: "창의성" },
      { english: "imagination", korean: "상상력" },
      { english: "opportunity", korean: "기회" },
      { english: "experience", korean: "경험" },
      { english: "knowledge", korean: "지식" },
      { english: "education", korean: "교육" },
      { english: "society", korean: "사회" },
      { english: "community", korean: "공동체" },
      { english: "relationship", korean: "관계" },
      { english: "friendship", korean: "우정" },
      { english: "trust", korean: "신뢰" },
      // 형용사 심화
      { english: "efficient", korean: "효율적인" },
      { english: "effective", korean: "효과적인" },
      { english: "necessary", korean: "필요한" },
      { english: "possible", korean: "가능한" },
      { english: "impossible", korean: "불가능한" },
      { english: "responsible", korean: "책임감 있는" },
      { english: "independent", korean: "독립적인" },
      { english: "creative", korean: "창의적인" },
      { english: "innovative", korean: "혁신적인" },
      { english: "traditional", korean: "전통적인" },
      { english: "modern", korean: "현대적인" },
      { english: "ancient", korean: "고대의" },
      { english: "global", korean: "세계적인" },
      { english: "local", korean: "지역의" },
      { english: "national", korean: "국가의" },
      { english: "international", korean: "국제적인" },
      { english: "economic", korean: "경제적인" },
      { english: "political", korean: "정치적인" },
      { english: "scientific", korean: "과학적인" },
      { english: "environmental", korean: "환경적인" },
      // 세계/지리
      { english: "continent", korean: "대륙" },
      { english: "country", korean: "나라" },
      { english: "capital", korean: "수도" },
      { english: "border", korean: "국경" },
      { english: "population", korean: "인구" },
      { english: "north", korean: "북쪽" },
      { english: "south", korean: "남쪽" },
      { english: "east", korean: "동쪽" },
      { english: "west", korean: "서쪽" },
      { english: "direction", korean: "방향" },
      // 경제/일상
      { english: "economy", korean: "경제" },
      { english: "trade", korean: "무역" },
      { english: "export", korean: "수출" },
      { english: "import", korean: "수입" },
      { english: "industry", korean: "산업" },
      { english: "product", korean: "제품" },
      { english: "customer", korean: "고객" },
      { english: "service", korean: "서비스" },
      { english: "advertisement", korean: "광고" },
      { english: "discount", korean: "할인" },
      // 미디어/문화
      { english: "novel", korean: "소설" },
      { english: "poem", korean: "시" },
      { english: "drama", korean: "드라마" },
      { english: "comedy", korean: "코미디" },
      { english: "cartoon", korean: "만화" },
      { english: "animation", korean: "애니메이션" },
      { english: "documentary", korean: "다큐멘터리" },
      { english: "concert", korean: "콘서트" },
      { english: "exhibition", korean: "전시회" },
      { english: "performance", korean: "공연" },
      // 추가 단어
      { english: "opinion", korean: "의견" },
      { english: "idea", korean: "아이디어" },
      { english: "theory", korean: "이론" },
      { english: "fact", korean: "사실" },
      { english: "evidence", korean: "증거" },
      { english: "example", korean: "예시" },
      { english: "reason", korean: "이유" },
      { english: "result", korean: "결과" },
      { english: "cause", korean: "원인" },
      { english: "effect", korean: "영향, 효과" },
      { english: "problem", korean: "문제" },
      { english: "solution", korean: "해결책" },
      { english: "goal", korean: "목표" },
      { english: "plan", korean: "계획" },
      { english: "step", korean: "단계" },
      { english: "process", korean: "과정" },
      { english: "method", korean: "방법" },
      { english: "system", korean: "시스템" },
      { english: "structure", korean: "구조" },
      { english: "pattern", korean: "패턴" },
      { english: "difference", korean: "차이" },
      { english: "similarity", korean: "유사점" },
      { english: "advantage", korean: "장점" },
      { english: "disadvantage", korean: "단점" },
      { english: "benefit", korean: "이익" },
      { english: "risk", korean: "위험" },
      { english: "choice", korean: "선택" },
      { english: "decision", korean: "결정" },
      { english: "agreement", korean: "동의, 계약" },
      { english: "conflict", korean: "갈등" },
      { english: "competition", korean: "경쟁" },
      { english: "cooperation", korean: "협력" },
      { english: "communication", korean: "소통" },
      { english: "information", korean: "정보" },
      { english: "data", korean: "데이터" },
      { english: "research", korean: "연구" },
      { english: "experiment", korean: "실험" },
      { english: "observation", korean: "관찰" },
      { english: "conclusion", korean: "결론" },
      { english: "report", korean: "보고서" },
      { english: "presentation", korean: "발표" },
      { english: "discussion", korean: "토론" },
      { english: "debate", korean: "논쟁" },
      { english: "interview", korean: "인터뷰" },
      { english: "survey", korean: "설문조사" },
      { english: "statistics", korean: "통계" },
      { english: "graph", korean: "그래프" },
      { english: "chart", korean: "차트" },
      { english: "diagram", korean: "다이어그램" },
      { english: "symbol", korean: "기호" },
      { english: "meaning", korean: "의미" },
      { english: "definition", korean: "정의" },
      { english: "concept", korean: "개념" },
      { english: "principle", korean: "원칙" },
      { english: "rule", korean: "규칙" },
      { english: "regulation", korean: "규정" },
      { english: "standard", korean: "기준" },
      { english: "quality", korean: "질, 품질" },
      { english: "quantity", korean: "양" },
      { english: "value", korean: "가치" },
      { english: "importance", korean: "중요성" },
      { english: "purpose", korean: "목적" },
      { english: "function", korean: "기능" },
      { english: "role", korean: "역할" },
      { english: "impact", korean: "영향" },
      { english: "change", korean: "변화" },
      { english: "development", korean: "발전" },
      { english: "progress", korean: "진보" },
      { english: "growth", korean: "성장" },
      { english: "challenge", korean: "도전, 어려움" },
      { english: "achievement", korean: "성취" },
      { english: "award", korean: "상" },
      { english: "prize", korean: "상금, 상품" },
      { english: "competition", korean: "대회" },
      { english: "champion", korean: "챔피언" },
      { english: "victory", korean: "승리" },
      { english: "defeat", korean: "패배" },
      { english: "talent", korean: "재능" },
      { english: "skill", korean: "기술, 실력" },
      { english: "ability", korean: "능력" },
      { english: "effort", korean: "노력" },
      { english: "career", korean: "직업, 경력" },
      { english: "workplace", korean: "직장" },
      { english: "colleague", korean: "동료" },
      { english: "salary", korean: "월급" },
      { english: "volunteer", korean: "자원봉사자" },
      { english: "charity", korean: "자선" },
      { english: "donate", korean: "기부하다" },
      { english: "poverty", korean: "가난" },
      { english: "wealth", korean: "부, 재산" },
      { english: "equality", korean: "평등" },
      { english: "justice", korean: "정의" },
      { english: "rights", korean: "권리" },
      { english: "duty", korean: "의무" },
      { english: "ethics", korean: "윤리" },
      { english: "moral", korean: "도덕적인" },
      { english: "attitude", korean: "태도" },
      { english: "behavior", korean: "행동" },
      { english: "habit", korean: "습관" },
      { english: "character", korean: "성격" },
      { english: "personality", korean: "개성" },
      { english: "confidence", korean: "자신감" },
      { english: "leadership", korean: "리더십" },
      { english: "teamwork", korean: "팀워크" },
      { english: "passion", korean: "열정" },
    ],
  },
];

async function main() {
  // 관리자 교사 계정
  const hash = await bcrypt.hash("admin1234", 10);
  await prisma.teacher.upsert({
    where: { email: "admin@wordchallenge.com" },
    update: {},
    create: { name: "관리자", email: "admin@wordchallenge.com", passwordHash: hash, isAdmin: true },
  });
  console.log("✅ 관리자 계정 생성");

  // 기존 단어장 모두 삭제 후 재생성
  await prisma.word.deleteMany({});
  await prisma.wordSet.deleteMany({});
  console.log("🗑️  기존 단어장 초기화");

  let totalWords = 0;
  for (let i = 0; i < WORD_SETS.length; i++) {
    const { name, emoji, description, words } = WORD_SETS[i];
    const ws = await prisma.wordSet.create({
      data: { name, emoji, description, isBuiltIn: true, order: i + 1 },
    });
    for (let j = 0; j < words.length; j++) {
      await prisma.word.create({
        data: { wordSetId: ws.id, english: words[j].english, korean: words[j].korean, order: j + 1 },
      });
    }
    totalWords += words.length;
    console.log(`✅ ${name} 생성 완료 (${words.length}개)`);
  }

  console.log(`\n🌱 시드 완료! 총 ${totalWords}개 단어`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
