import { NextResponse } from "next/server";
import { getTeacherId } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const HIGH_WORDS: Record<string, { english: string; korean: string }[]> = {
  "고1": [
    { english: "abandon", korean: "버리다" }, { english: "abroad", korean: "해외에" }, { english: "absence", korean: "부재" },
    { english: "abstract", korean: "추상적인" }, { english: "academic", korean: "학문적인" }, { english: "access", korean: "접근하다" },
    { english: "accomplish", korean: "성취하다" }, { english: "according", korean: "~에 따르면" }, { english: "accurate", korean: "정확한" },
    { english: "achieve", korean: "달성하다" }, { english: "acquire", korean: "습득하다" }, { english: "adapt", korean: "적응하다" },
    { english: "additional", korean: "추가적인" }, { english: "adequate", korean: "적절한" }, { english: "admit", korean: "인정하다" },
    { english: "adopt", korean: "채택하다" }, { english: "advance", korean: "발전시키다" }, { english: "advantage", korean: "장점" },
    { english: "affect", korean: "영향을 미치다" }, { english: "afford", korean: "여유가 있다" }, { english: "afterward", korean: "나중에" },
    { english: "agency", korean: "기관" }, { english: "aggressive", korean: "공격적인" }, { english: "agree", korean: "동의하다" },
    { english: "agriculture", korean: "농업" }, { english: "aim", korean: "목표" }, { english: "alert", korean: "경계하는" },
    { english: "allow", korean: "허용하다" }, { english: "alter", korean: "바꾸다" }, { english: "alternative", korean: "대안" },
    { english: "analyze", korean: "분석하다" }, { english: "ancient", korean: "고대의" }, { english: "announce", korean: "발표하다" },
    { english: "anticipate", korean: "예상하다" }, { english: "anxiety", korean: "불안" }, { english: "apologize", korean: "사과하다" },
    { english: "apparent", korean: "명백한" }, { english: "appeal", korean: "호소하다" }, { english: "apply", korean: "지원하다" },
    { english: "appreciate", korean: "감사하다" }, { english: "appropriate", korean: "적절한" }, { english: "approve", korean: "승인하다" },
    { english: "argue", korean: "주장하다" }, { english: "arrange", korean: "준비하다" }, { english: "artificial", korean: "인공의" },
    { english: "aspect", korean: "측면" }, { english: "assist", korean: "돕다" }, { english: "assume", korean: "가정하다" },
    { english: "atmosphere", korean: "분위기" }, { english: "attach", korean: "첨부하다" }, { english: "attempt", korean: "시도하다" },
    { english: "attitude", korean: "태도" }, { english: "attract", korean: "끌어들이다" }, { english: "authority", korean: "권위" },
    { english: "available", korean: "이용 가능한" }, { english: "average", korean: "평균" }, { english: "avoid", korean: "피하다" },
    { english: "aware", korean: "인식하는" }, { english: "background", korean: "배경" }, { english: "barrier", korean: "장벽" },
    { english: "basis", korean: "근거" }, { english: "behavior", korean: "행동" }, { english: "benefit", korean: "이점" },
    { english: "blame", korean: "비난하다" }, { english: "border", korean: "경계" }, { english: "budget", korean: "예산" },
    { english: "capacity", korean: "능력" }, { english: "career", korean: "직업" }, { english: "category", korean: "범주" },
    { english: "certain", korean: "확실한" }, { english: "challenge", korean: "도전" }, { english: "citizen", korean: "시민" },
    { english: "claim", korean: "주장하다" }, { english: "climate", korean: "기후" }, { english: "combine", korean: "결합하다" },
    { english: "communicate", korean: "소통하다" }, { english: "community", korean: "지역 사회" }, { english: "compare", korean: "비교하다" },
    { english: "compete", korean: "경쟁하다" }, { english: "concentrate", korean: "집중하다" }, { english: "concern", korean: "우려" },
    { english: "condition", korean: "조건" }, { english: "confident", korean: "자신 있는" }, { english: "conflict", korean: "갈등" },
    { english: "connect", korean: "연결하다" }, { english: "consider", korean: "고려하다" }, { english: "consist", korean: "구성되다" },
    { english: "consume", korean: "소비하다" }, { english: "contain", korean: "포함하다" }, { english: "contribute", korean: "기여하다" },
    { english: "convenient", korean: "편리한" }, { english: "cooperate", korean: "협력하다" }, { english: "creative", korean: "창의적인" },
    { english: "crime", korean: "범죄" }, { english: "cultural", korean: "문화적인" }, { english: "curious", korean: "호기심 많은" },
    { english: "current", korean: "현재의" }, { english: "damage", korean: "손해" }, { english: "debate", korean: "토론하다" },
    { english: "decade", korean: "10년" }, { english: "decrease", korean: "감소하다" }, { english: "define", korean: "정의하다" },
    { english: "delay", korean: "지연시키다" }, { english: "demand", korean: "요구하다" }, { english: "depend", korean: "의존하다" },
    { english: "describe", korean: "묘사하다" }, { english: "deserve", korean: "~을 받을 자격이 있다" }, { english: "determine", korean: "결정하다" },
    { english: "develop", korean: "발전시키다" }, { english: "device", korean: "장치" }, { english: "diet", korean: "식단" },
    { english: "disappear", korean: "사라지다" }, { english: "discipline", korean: "훈련" }, { english: "discover", korean: "발견하다" },
    { english: "discuss", korean: "토의하다" }, { english: "disease", korean: "질병" }, { english: "divide", korean: "나누다" },
    { english: "document", korean: "문서" }, { english: "doubt", korean: "의심하다" }, { english: "dramatic", korean: "극적인" },
    { english: "earn", korean: "벌다" }, { english: "ecosystem", korean: "생태계" }, { english: "effective", korean: "효과적인" },
    { english: "efficient", korean: "효율적인" }, { english: "effort", korean: "노력" }, { english: "emotion", korean: "감정" },
    { english: "encourage", korean: "격려하다" }, { english: "energy", korean: "에너지" }, { english: "environment", korean: "환경" },
    { english: "equal", korean: "평등한" }, { english: "establish", korean: "설립하다" }, { english: "event", korean: "행사" },
    { english: "evidence", korean: "증거" }, { english: "examine", korean: "검사하다" }, { english: "exist", korean: "존재하다" },
    { english: "expand", korean: "확장하다" }, { english: "expect", korean: "기대하다" }, { english: "experiment", korean: "실험" },
    { english: "expert", korean: "전문가" }, { english: "explore", korean: "탐험하다" }, { english: "express", korean: "표현하다" },
    { english: "extend", korean: "연장하다" }, { english: "factor", korean: "요인" }, { english: "feature", korean: "특징" },
    { english: "focus", korean: "집중하다" }, { english: "force", korean: "강요하다" }, { english: "formal", korean: "공식적인" },
    { english: "freedom", korean: "자유" }, { english: "frequent", korean: "빈번한" }, { english: "function", korean: "기능" },
    { english: "gain", korean: "얻다" }, { english: "general", korean: "일반적인" }, { english: "generate", korean: "생성하다" },
    { english: "global", korean: "세계적인" }, { english: "government", korean: "정부" }, { english: "gradually", korean: "점차" },
    { english: "grateful", korean: "감사하는" }, { english: "habitat", korean: "서식지" }, { english: "harmful", korean: "해로운" },
    { english: "heritage", korean: "유산" }, { english: "highlight", korean: "강조하다" }, { english: "hire", korean: "고용하다" },
    { english: "identify", korean: "확인하다" }, { english: "ignore", korean: "무시하다" }, { english: "imagine", korean: "상상하다" },
    { english: "impact", korean: "영향" }, { english: "improve", korean: "향상시키다" }, { english: "include", korean: "포함하다" },
    { english: "increase", korean: "증가하다" }, { english: "indicate", korean: "나타내다" }, { english: "influence", korean: "영향" },
    { english: "inform", korean: "알리다" }, { english: "inspire", korean: "영감을 주다" }, { english: "interact", korean: "상호작용하다" },
    { english: "involve", korean: "관련시키다" }, { english: "issue", korean: "문제" }, { english: "journey", korean: "여정" },
    { english: "justice", korean: "정의" }, { english: "knowledge", korean: "지식" }, { english: "launch", korean: "시작하다" },
    { english: "limit", korean: "제한하다" }, { english: "local", korean: "지역의" }, { english: "maintain", korean: "유지하다" },
    { english: "major", korean: "주요한" }, { english: "manage", korean: "관리하다" }, { english: "material", korean: "재료" },
    { english: "mental", korean: "정신적인" }, { english: "method", korean: "방법" }, { english: "mission", korean: "임무" },
    { english: "modern", korean: "현대의" }, { english: "multiple", korean: "다수의" }, { english: "necessary", korean: "필요한" },
    { english: "negative", korean: "부정적인" }, { english: "nervous", korean: "긴장한" }, { english: "notice", korean: "알아채다" },
    { english: "objective", korean: "목표" }, { english: "observe", korean: "관찰하다" }, { english: "occur", korean: "발생하다" },
    { english: "official", korean: "공식적인" }, { english: "opportunity", korean: "기회" }, { english: "organization", korean: "조직" },
    { english: "overcome", korean: "극복하다" }, { english: "participate", korean: "참여하다" }, { english: "passion", korean: "열정" },
    { english: "perform", korean: "수행하다" }, { english: "period", korean: "기간" }, { english: "physical", korean: "신체적인" },
    { english: "policy", korean: "정책" }, { english: "pollution", korean: "오염" }, { english: "population", korean: "인구" },
    { english: "positive", korean: "긍정적인" }, { english: "poverty", korean: "빈곤" }, { english: "predict", korean: "예측하다" },
    { english: "prevent", korean: "예방하다" }, { english: "process", korean: "과정" }, { english: "produce", korean: "생산하다" },
    { english: "progress", korean: "진전" }, { english: "promote", korean: "촉진하다" }, { english: "protect", korean: "보호하다" },
    { english: "provide", korean: "제공하다" }, { english: "purpose", korean: "목적" }, { english: "quality", korean: "품질" },
    { english: "reduce", korean: "줄이다" }, { english: "reflect", korean: "반영하다" }, { english: "region", korean: "지역" },
    { english: "relationship", korean: "관계" }, { english: "release", korean: "출시하다" }, { english: "replace", korean: "교체하다" },
    { english: "require", korean: "요구하다" }, { english: "research", korean: "연구" }, { english: "resource", korean: "자원" },
    { english: "respond", korean: "반응하다" }, { english: "result", korean: "결과" }, { english: "review", korean: "검토하다" },
    { english: "reward", korean: "보상" }, { english: "risk", korean: "위험" }, { english: "role", korean: "역할" },
    { english: "satisfy", korean: "만족시키다" }, { english: "select", korean: "선택하다" }, { english: "separate", korean: "분리하다" },
    { english: "significant", korean: "중요한" }, { english: "situation", korean: "상황" }, { english: "society", korean: "사회" },
    { english: "solution", korean: "해결책" }, { english: "species", korean: "종" }, { english: "standard", korean: "기준" },
    { english: "strategy", korean: "전략" }, { english: "structure", korean: "구조" }, { english: "struggle", korean: "분투하다" },
    { english: "succeed", korean: "성공하다" }, { english: "suggest", korean: "제안하다" }, { english: "support", korean: "지지하다" },
    { english: "survive", korean: "생존하다" }, { english: "symbol", korean: "상징" }, { english: "talent", korean: "재능" },
    { english: "technology", korean: "기술" }, { english: "tradition", korean: "전통" }, { english: "transform", korean: "변환하다" },
    { english: "trend", korean: "추세" }, { english: "trust", korean: "신뢰하다" }, { english: "unique", korean: "독특한" },
    { english: "valuable", korean: "가치 있는" }, { english: "variety", korean: "다양성" }, { english: "violence", korean: "폭력" },
    { english: "virtual", korean: "가상의" }, { english: "volunteer", korean: "자원봉사하다" }, { english: "wealth", korean: "부" },
    { english: "widespread", korean: "광범위한" }, { english: "willing", korean: "기꺼이 하는" }, { english: "wisdom", korean: "지혜" },
  ],
  "고2": [
    { english: "abolish", korean: "폐지하다" }, { english: "absorb", korean: "흡수하다" }, { english: "accelerate", korean: "가속하다" },
    { english: "accessible", korean: "접근 가능한" }, { english: "accommodate", korean: "수용하다" }, { english: "acknowledge", korean: "인정하다" },
    { english: "activate", korean: "활성화하다" }, { english: "address", korean: "다루다" }, { english: "advocate", korean: "지지하다" },
    { english: "allocate", korean: "할당하다" }, { english: "ambiguous", korean: "모호한" }, { english: "ambitious", korean: "야망 있는" },
    { english: "amend", korean: "수정하다" }, { english: "ample", korean: "충분한" }, { english: "anticipate", korean: "예상하다" },
    { english: "arbitrary", korean: "임의적인" }, { english: "assess", korean: "평가하다" }, { english: "assumption", korean: "가정" },
    { english: "assure", korean: "보장하다" }, { english: "authentic", korean: "진정한" }, { english: "authority", korean: "권위" },
    { english: "autonomy", korean: "자율성" }, { english: "bankruptcy", korean: "파산" }, { english: "bias", korean: "편견" },
    { english: "biodiversity", korean: "생물 다양성" }, { english: "breakthrough", korean: "돌파구" }, { english: "bureaucracy", korean: "관료주의" },
    { english: "catastrophe", korean: "재앙" }, { english: "cease", korean: "그치다" }, { english: "censorship", korean: "검열" },
    { english: "circumstance", korean: "상황" }, { english: "collaborate", korean: "협력하다" }, { english: "commitment", korean: "헌신" },
    { english: "commodity", korean: "상품" }, { english: "compensate", korean: "보상하다" }, { english: "competent", korean: "유능한" },
    { english: "complement", korean: "보완하다" }, { english: "complex", korean: "복잡한" }, { english: "comply", korean: "따르다" },
    { english: "concept", korean: "개념" }, { english: "conclude", korean: "결론짓다" }, { english: "consequence", korean: "결과" },
    { english: "consistency", korean: "일관성" }, { english: "construct", korean: "건설하다" }, { english: "contradict", korean: "반박하다" },
    { english: "controversy", korean: "논란" }, { english: "convert", korean: "전환하다" }, { english: "coordinate", korean: "조율하다" },
    { english: "credible", korean: "신뢰할 수 있는" }, { english: "critical", korean: "비판적인" }, { english: "crucial", korean: "중요한" },
    { english: "cultivate", korean: "경작하다" }, { english: "curriculum", korean: "교육과정" }, { english: "decay", korean: "부패하다" },
    { english: "dedicate", korean: "헌신하다" }, { english: "defend", korean: "방어하다" }, { english: "deforestation", korean: "삼림 벌채" },
    { english: "deliberate", korean: "신중한" }, { english: "demonstrate", korean: "증명하다" }, { english: "deny", korean: "부정하다" },
    { english: "detect", korean: "감지하다" }, { english: "devote", korean: "헌신하다" }, { english: "dilemma", korean: "딜레마" },
    { english: "diminish", korean: "줄어들다" }, { english: "discrimination", korean: "차별" }, { english: "dispute", korean: "분쟁" },
    { english: "distribute", korean: "분배하다" }, { english: "diverse", korean: "다양한" }, { english: "dominant", korean: "지배적인" },
    { english: "drought", korean: "가뭄" }, { english: "dynamic", korean: "역동적인" }, { english: "elaborate", korean: "정교한" },
    { english: "eliminate", korean: "제거하다" }, { english: "emphasize", korean: "강조하다" }, { english: "empower", korean: "권한을 부여하다" },
    { english: "enforce", korean: "시행하다" }, { english: "enhance", korean: "향상시키다" }, { english: "ensure", korean: "보장하다" },
    { english: "epidemic", korean: "전염병" }, { english: "equality", korean: "평등" }, { english: "equivalent", korean: "동등한" },
    { english: "ethical", korean: "윤리적인" }, { english: "evaluate", korean: "평가하다" }, { english: "evolve", korean: "진화하다" },
    { english: "exclusive", korean: "독점적인" }, { english: "execute", korean: "실행하다" }, { english: "exhaust", korean: "고갈시키다" },
    { english: "explicit", korean: "명확한" }, { english: "exploit", korean: "착취하다" }, { english: "facilitate", korean: "촉진하다" },
    { english: "feasible", korean: "실현 가능한" }, { english: "flaw", korean: "결함" }, { english: "flexible", korean: "유연한" },
    { english: "flourish", korean: "번성하다" }, { english: "formulate", korean: "공식화하다" }, { english: "foster", korean: "육성하다" },
    { english: "foundation", korean: "기초" }, { english: "fragile", korean: "취약한" }, { english: "fraud", korean: "사기" },
    { english: "fundamental", korean: "근본적인" }, { english: "genuine", korean: "진정한" }, { english: "gradual", korean: "점진적인" },
    { english: "gravity", korean: "중력" }, { english: "hierarchy", korean: "계층 구조" }, { english: "hypothesis", korean: "가설" },
    { english: "identical", korean: "동일한" }, { english: "ideology", korean: "이데올로기" }, { english: "illusion", korean: "환상" },
    { english: "implement", korean: "시행하다" }, { english: "implicit", korean: "암묵적인" }, { english: "indispensable", korean: "필수적인" },
    { english: "inequality", korean: "불평등" }, { english: "inevitable", korean: "불가피한" }, { english: "infrastructure", korean: "인프라" },
    { english: "inherent", korean: "고유한" }, { english: "initiative", korean: "주도권" }, { english: "innovation", korean: "혁신" },
    { english: "integrate", korean: "통합하다" }, { english: "integrity", korean: "진실성" }, { english: "intellectual", korean: "지적인" },
    { english: "interpret", korean: "해석하다" }, { english: "intervene", korean: "개입하다" }, { english: "invest", korean: "투자하다" },
    { english: "justify", korean: "정당화하다" }, { english: "legislation", korean: "법률" }, { english: "legitimate", korean: "합법적인" },
    { english: "liberty", korean: "자유" }, { english: "manipulate", korean: "조작하다" }, { english: "mechanism", korean: "메커니즘" },
    { english: "mediate", korean: "조정하다" }, { english: "minimize", korean: "최소화하다" }, { english: "moderate", korean: "온건한" },
    { english: "momentum", korean: "추진력" }, { english: "monitor", korean: "감시하다" }, { english: "motivate", korean: "동기를 부여하다" },
    { english: "mutual", korean: "상호의" }, { english: "narrative", korean: "서술" }, { english: "neutral", korean: "중립적인" },
    { english: "numerous", korean: "다수의" }, { english: "obligation", korean: "의무" }, { english: "obtain", korean: "얻다" },
    { english: "oppose", korean: "반대하다" }, { english: "optimistic", korean: "낙관적인" }, { english: "outcome", korean: "결과" },
    { english: "overwhelm", korean: "압도하다" }, { english: "perceive", korean: "인식하다" }, { english: "persistent", korean: "지속적인" },
    { english: "perspective", korean: "관점" }, { english: "phenomenon", korean: "현상" }, { english: "philosophy", korean: "철학" },
    { english: "potential", korean: "잠재력" }, { english: "precisely", korean: "정확하게" }, { english: "prestigious", korean: "명망 있는" },
    { english: "principle", korean: "원칙" }, { english: "privilege", korean: "특권" }, { english: "profound", korean: "심오한" },
    { english: "propaganda", korean: "선전" }, { english: "prospect", korean: "전망" }, { english: "pursuit", korean: "추구" },
    { english: "radical", korean: "급진적인" }, { english: "realistic", korean: "현실적인" }, { english: "recognize", korean: "인식하다" },
    { english: "reform", korean: "개혁하다" }, { english: "reinforce", korean: "강화하다" }, { english: "relevant", korean: "관련 있는" },
    { english: "reluctant", korean: "내키지 않는" }, { english: "remarkable", korean: "놀라운" }, { english: "resolve", korean: "해결하다" },
    { english: "restrain", korean: "억제하다" }, { english: "retain", korean: "유지하다" }, { english: "reveal", korean: "드러내다" },
    { english: "rigorous", korean: "엄격한" }, { english: "robust", korean: "강건한" }, { english: "sacrifice", korean: "희생하다" },
    { english: "scholar", korean: "학자" }, { english: "scrutiny", korean: "면밀한 검토" }, { english: "simultaneously", korean: "동시에" },
    { english: "sophisticated", korean: "정교한" }, { english: "specific", korean: "구체적인" }, { english: "speculation", korean: "추측" },
    { english: "stable", korean: "안정적인" }, { english: "statistics", korean: "통계" }, { english: "stereotype", korean: "고정관념" },
    { english: "stimulus", korean: "자극" }, { english: "subsequent", korean: "그 다음의" }, { english: "substantial", korean: "상당한" },
    { english: "subtle", korean: "미묘한" }, { english: "sufficient", korean: "충분한" }, { english: "suppress", korean: "억압하다" },
    { english: "sustainable", korean: "지속 가능한" }, { english: "thorough", korean: "철저한" }, { english: "tolerance", korean: "관용" },
    { english: "transparent", korean: "투명한" }, { english: "ultimate", korean: "궁극적인" }, { english: "undermine", korean: "약화시키다" },
    { english: "universal", korean: "보편적인" }, { english: "unprecedented", korean: "전례 없는" }, { english: "utilize", korean: "활용하다" },
    { english: "valid", korean: "유효한" }, { english: "verify", korean: "확인하다" }, { english: "virtually", korean: "사실상" },
    { english: "vital", korean: "필수적인" }, { english: "vulnerable", korean: "취약한" }, { english: "yield", korean: "산출하다" },
    { english: "abolition", korean: "폐지" }, { english: "acknowledge", korean: "인정하다" }, { english: "aggregate", korean: "집합체" },
    { english: "alienate", korean: "소외시키다" }, { english: "allege", korean: "주장하다" }, { english: "ambivalent", korean: "양면적인" },
    { english: "analogy", korean: "유추" }, { english: "annihilate", korean: "전멸시키다" }, { english: "anomaly", korean: "이상" },
    { english: "articulate", korean: "표현하다" }, { english: "attain", korean: "달성하다" }, { english: "attribute", korean: "귀인하다" },
    { english: "benevolent", korean: "자비로운" }, { english: "candid", korean: "솔직한" }, { english: "catalyst", korean: "촉매제" },
    { english: "chronological", korean: "연대순의" }, { english: "coerce", korean: "강요하다" }, { english: "coherent", korean: "일관된" },
    { english: "coincide", korean: "일치하다" }, { english: "collective", korean: "집단적인" }, { english: "compassion", korean: "연민" },
    { english: "compelling", korean: "강력한" }, { english: "conceive", korean: "생각해 내다" }, { english: "conform", korean: "순응하다" },
    { english: "conscientious", korean: "성실한" }, { english: "consensus", korean: "합의" }, { english: "contraband", korean: "밀수품" },
    { english: "convey", korean: "전달하다" }, { english: "correlation", korean: "상관관계" },
  ],
  "고3": [
    { english: "abridge", korean: "요약하다" }, { english: "abstain", korean: "자제하다" }, { english: "accentuate", korean: "강조하다" },
    { english: "acclaim", korean: "갈채를 보내다" }, { english: "acrimony", korean: "신랄함" }, { english: "adept", korean: "능숙한" },
    { english: "adhere", korean: "고수하다" }, { english: "adjacent", korean: "인접한" }, { english: "adverse", korean: "불리한" },
    { english: "affirmative", korean: "긍정적인" }, { english: "affluent", korean: "부유한" }, { english: "aggravate", korean: "악화시키다" },
    { english: "aggregate", korean: "합산하다" }, { english: "alleviate", korean: "완화하다" }, { english: "allot", korean: "할당하다" },
    { english: "altruistic", korean: "이타적인" }, { english: "ambivalence", korean: "양면성" }, { english: "ameliorate", korean: "개선하다" },
    { english: "analogy", korean: "유추" }, { english: "antagonist", korean: "적대자" }, { english: "apathy", korean: "무관심" },
    { english: "apprehend", korean: "이해하다" }, { english: "apt", korean: "적절한" }, { english: "arduous", korean: "힘든" },
    { english: "articulate", korean: "명확히 표현하다" }, { english: "aspire", korean: "열망하다" }, { english: "astute", korean: "명민한" },
    { english: "atrocity", korean: "잔혹 행위" }, { english: "attain", korean: "달성하다" }, { english: "attribute", korean: "귀인하다" },
    { english: "augment", korean: "증대하다" }, { english: "austere", korean: "엄격한" }, { english: "axiom", korean: "공리" },
    { english: "benevolent", korean: "자비로운" }, { english: "benign", korean: "양성의" }, { english: "bolster", korean: "강화하다" },
    { english: "brevity", korean: "간결함" }, { english: "candid", korean: "솔직한" }, { english: "catalyst", korean: "촉매제" },
    { english: "causality", korean: "인과관계" }, { english: "circumvent", korean: "우회하다" }, { english: "clamor", korean: "외침" },
    { english: "coerce", korean: "강요하다" }, { english: "cogent", korean: "설득력 있는" }, { english: "coherent", korean: "일관된" },
    { english: "coincide", korean: "일치하다" }, { english: "collective", korean: "집단적인" }, { english: "compassion", korean: "연민" },
    { english: "compelling", korean: "강력한" }, { english: "concede", korean: "인정하다" }, { english: "conceive", korean: "생각해 내다" },
    { english: "condone", korean: "묵인하다" }, { english: "confound", korean: "혼란스럽게 하다" }, { english: "conform", korean: "순응하다" },
    { english: "conjecture", korean: "추측" }, { english: "conscientious", korean: "성실한" }, { english: "consensus", korean: "합의" },
    { english: "consolidate", korean: "통합하다" }, { english: "constrain", korean: "제약하다" }, { english: "contemplate", korean: "숙고하다" },
    { english: "contentious", korean: "논쟁적인" }, { english: "conviction", korean: "신념" }, { english: "convey", korean: "전달하다" },
    { english: "correlation", korean: "상관관계" }, { english: "corroborate", korean: "확증하다" }, { english: "counterfeit", korean: "위조하다" },
    { english: "daunting", korean: "버거운" }, { english: "debilitate", korean: "약화시키다" }, { english: "deduce", korean: "추론하다" },
    { english: "deficient", korean: "결핍된" }, { english: "degenerate", korean: "퇴화하다" }, { english: "denounce", korean: "비난하다" },
    { english: "deplete", korean: "고갈시키다" }, { english: "derive", korean: "도출하다" }, { english: "detrimental", korean: "해로운" },
    { english: "devious", korean: "교활한" }, { english: "differentiate", korean: "구별하다" }, { english: "dignity", korean: "존엄성" },
    { english: "discern", korean: "분별하다" }, { english: "discourse", korean: "담론" }, { english: "dismantle", korean: "해체하다" },
    { english: "disparate", korean: "이질적인" }, { english: "disposition", korean: "성향" }, { english: "dissent", korean: "반대하다" },
    { english: "distort", korean: "왜곡하다" }, { english: "diverge", korean: "갈라지다" }, { english: "doctrine", korean: "교리" },
    { english: "elude", korean: "피하다" }, { english: "embody", korean: "구체화하다" }, { english: "empirical", korean: "경험적인" },
    { english: "endorse", korean: "지지하다" }, { english: "engender", korean: "야기하다" }, { english: "entail", korean: "수반하다" },
    { english: "erroneous", korean: "잘못된" }, { english: "espouse", korean: "지지하다" }, { english: "exacerbate", korean: "악화시키다" },
    { english: "exert", korean: "발휘하다" }, { english: "exemplify", korean: "예시하다" }, { english: "exorbitant", korean: "과도한" },
    { english: "expedient", korean: "편의적인" }, { english: "extrapolate", korean: "외삽하다" }, { english: "fabricate", korean: "조작하다" },
    { english: "fallacy", korean: "오류" }, { english: "fortify", korean: "강화하다" }, { english: "futile", korean: "헛된" },
    { english: "grievance", korean: "불만" }, { english: "hamper", korean: "방해하다" }, { english: "hinder", korean: "방해하다" },
    { english: "imminent", korean: "임박한" }, { english: "impartial", korean: "공정한" }, { english: "impede", korean: "방해하다" },
    { english: "implication", korean: "함의" }, { english: "inadvertent", korean: "의도치 않은" }, { english: "incline", korean: "기울어지다" },
    { english: "inconclusive", korean: "결론이 나지 않는" }, { english: "induce", korean: "유도하다" }, { english: "infer", korean: "추론하다" },
    { english: "ingenious", korean: "독창적인" }, { english: "inherently", korean: "본질적으로" }, { english: "inhibit", korean: "억제하다" },
    { english: "instigate", korean: "선동하다" }, { english: "integral", korean: "필수적인" }, { english: "intrinsic", korean: "본질적인" },
    { english: "irrefutable", korean: "반박할 수 없는" }, { english: "jeopardize", korean: "위태롭게 하다" }, { english: "lament", korean: "슬퍼하다" },
    { english: "latent", korean: "잠재적인" }, { english: "lenient", korean: "관대한" }, { english: "lucid", korean: "명쾌한" },
    { english: "meticulous", korean: "꼼꼼한" }, { english: "mitigate", korean: "완화하다" }, { english: "mundane", korean: "평범한" },
    { english: "negate", korean: "부정하다" }, { english: "notion", korean: "개념" }, { english: "nuance", korean: "뉘앙스" },
    { english: "obscure", korean: "불분명한" }, { english: "obsolete", korean: "낡은" }, { english: "ominous", korean: "불길한" },
    { english: "opaque", korean: "불투명한" }, { english: "orthodox", korean: "정통적인" }, { english: "paramount", korean: "가장 중요한" },
    { english: "partisan", korean: "당파적인" }, { english: "passive", korean: "수동적인" }, { english: "pathos", korean: "애수" },
    { english: "perpetuate", korean: "영속시키다" }, { english: "pervasive", korean: "만연한" }, { english: "plausible", korean: "그럴듯한" },
    { english: "polarize", korean: "양극화하다" }, { english: "postulate", korean: "공리" }, { english: "pragmatic", korean: "실용적인" },
    { english: "preclude", korean: "배제하다" }, { english: "predominant", korean: "지배적인" }, { english: "premise", korean: "전제" },
    { english: "preoccupy", korean: "몰두하게 하다" }, { english: "prevalent", korean: "만연한" }, { english: "prolong", korean: "연장하다" },
    { english: "propagate", korean: "전파하다" }, { english: "provoke", korean: "유발하다" }, { english: "prudent", korean: "신중한" },
    { english: "qualitative", korean: "질적인" }, { english: "quantitative", korean: "양적인" }, { english: "rationale", korean: "근거" },
    { english: "reciprocal", korean: "상호적인" }, { english: "redundant", korean: "불필요한" }, { english: "refute", korean: "반박하다" },
    { english: "relentless", korean: "끊임없는" }, { english: "resilient", korean: "회복력 있는" }, { english: "resonate", korean: "공명하다" },
    { english: "revert", korean: "돌아가다" }, { english: "rhetoric", korean: "수사법" }, { english: "rigidity", korean: "경직성" },
    { english: "rudimentary", korean: "기초적인" }, { english: "scrutinize", korean: "면밀히 검토하다" }, { english: "self-evident", korean: "자명한" },
    { english: "skeptical", korean: "회의적인" }, { english: "sovereignty", korean: "주권" }, { english: "speculation", korean: "추측" },
    { english: "sporadic", korean: "산발적인" }, { english: "steadfast", korean: "확고한" }, { english: "stringent", korean: "엄격한" },
    { english: "subordinate", korean: "하위의" }, { english: "succumb", korean: "굴복하다" }, { english: "superfluous", korean: "불필요한" },
    { english: "susceptible", korean: "취약한" }, { english: "synthesize", korean: "종합하다" }, { english: "tacit", korean: "암묵적인" },
    { english: "tenacious", korean: "끈질긴" }, { english: "tentative", korean: "임시적인" }, { english: "testament", korean: "증거" },
    { english: "thwart", korean: "좌절시키다" }, { english: "transcend", korean: "초월하다" }, { english: "trivial", korean: "사소한" },
    { english: "ubiquitous", korean: "어디에나 있는" }, { english: "unilateral", korean: "일방적인" }, { english: "unravel", korean: "풀다" },
    { english: "upheaval", korean: "격변" }, { english: "vacillate", korean: "흔들리다" }, { english: "vindicate", korean: "정당화하다" },
    { english: "volatile", korean: "변동이 심한" }, { english: "wane", korean: "약해지다" }, { english: "warrant", korean: "정당화하다" },
    { english: "zealous", korean: "열성적인" }, { english: "ambivalent", korean: "양면적인" }, { english: "blatant", korean: "뻔뻔한" },
    { english: "circumspect", korean: "신중한" }, { english: "complacent", korean: "자기만족적인" }, { english: "convoluted", korean: "복잡한" },
    { english: "culminate", korean: "절정에 달하다" }, { english: "debunk", korean: "폭로하다" }, { english: "defiance", korean: "반항" },
    { english: "demise", korean: "종말" }, { english: "depict", korean: "묘사하다" }, { english: "disparity", korean: "불평등" },
    { english: "dubious", korean: "의심스러운" }, { english: "elusive", korean: "파악하기 힘든" }, { english: "enigmatic", korean: "수수께끼 같은" },
    { english: "ephemeral", korean: "덧없는" }, { english: "exquisite", korean: "정교한" }, { english: "fervent", korean: "열렬한" },
    { english: "grotesque", korean: "기괴한" }, { english: "holistic", korean: "전체론적인" }, { english: "hypocrisy", korean: "위선" },
    { english: "idiosyncratic", korean: "특이한" }, { english: "incessant", korean: "끊임없는" }, { english: "indignant", korean: "분개한" },
    { english: "infallible", korean: "오류가 없는" }, { english: "ingenuity", korean: "독창성" }, { english: "innocuous", korean: "무해한" },
  ],
};

export async function POST(req: Request) {
  const tid = await getTeacherId(req);
  if (!tid) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const results: Record<string, string> = {};

  for (const [gradeName, words] of Object.entries(HIGH_WORDS)) {
    let wordSet = await prisma.wordSet.findFirst({ where: { name: gradeName } });

    if (!wordSet) {
      const order = gradeName === "고1" ? 10 : gradeName === "고2" ? 11 : 12;
      const emoji = gradeName === "고1" ? "📕" : gradeName === "고2" ? "📙" : "📗";
      wordSet = await prisma.wordSet.create({
        data: { name: gradeName, description: `고등학교 ${gradeName.replace("고", "")}학년`, emoji, order },
      });
    }

    const existing = await prisma.word.count({ where: { wordSetId: wordSet.id } });
    if (existing > 0) {
      results[gradeName] = `이미 ${existing}개 단어 존재 (스킵)`;
      continue;
    }

    await prisma.word.createMany({
      data: words.map((w, i) => ({ wordSetId: wordSet!.id, english: w.english, korean: w.korean, order: i + 1 })),
    });
    results[gradeName] = `${words.length}개 단어 추가 완료`;
  }

  return NextResponse.json({ ok: true, results });
}
